// This file is auto-generated by @hey-api/openapi-ts

export const BrandSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        website_urls: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Website Urls'
        }
    },
    type: 'object',
    title: 'Brand',
    description: 'The brand a product belongs to, with its source website(s).'
} as const;

export const CatalogFiltersSchema = {
    properties: {
        brands: {
            items: {
                $ref: '#/components/schemas/FilterOption'
            },
            type: 'array',
            title: 'Brands',
            default: []
        },
        categories: {
            items: {
                $ref: '#/components/schemas/FilterOption'
            },
            type: 'array',
            title: 'Categories',
            default: []
        },
        seasons: {
            items: {
                $ref: '#/components/schemas/FilterOption'
            },
            type: 'array',
            title: 'Seasons',
            default: []
        },
        suppliers: {
            items: {
                $ref: '#/components/schemas/FilterOption'
            },
            type: 'array',
            title: 'Suppliers',
            default: []
        },
        tags: {
            items: {
                $ref: '#/components/schemas/FilterOption'
            },
            type: 'array',
            title: 'Tags',
            default: []
        }
    },
    type: 'object',
    title: 'CatalogFilters',
    description: 'Classification lists backing the product-search filters.'
} as const;

export const ExampleResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        sample_id: {
            type: 'integer',
            title: 'Sample Id'
        }
    },
    type: 'object',
    required: [
        'status',
        'message',
        'sample_id'
    ],
    title: 'ExampleResponse',
    description: 'Response payload returned by the example endpoint.'
} as const;

export const FilterOptionSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        }
    },
    type: 'object',
    required: [
        'id',
        'title'
    ],
    title: 'FilterOption',
    description: 'One selectable value in a search filter (brand, category, …).'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        status: {
            type: 'string',
            const: 'ok',
            title: 'Status'
        },
        database: {
            type: 'string',
            const: 'up',
            title: 'Database'
        }
    },
    type: 'object',
    required: [
        'status',
        'database'
    ],
    title: 'HealthResponse',
    description: 'Response returned by the healthcheck endpoint.'
} as const;

export const ItemPatchRequestSchema = {
    properties: {
        staged_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Title'
        },
        staged_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Description'
        },
        staged_meta: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Meta'
        },
        staged_images_json: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Images Json'
        },
        staged_weights_json: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Weights Json'
        }
    },
    type: 'object',
    title: 'ItemPatchRequest',
    description: 'Editable staged fields (review-time corrections).'
} as const;

export const ItemPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        job_id: {
            type: 'integer',
            title: 'Job Id'
        },
        tillin_product_id: {
            type: 'integer',
            title: 'Tillin Product Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        source_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Url'
        },
        source_method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Method'
        },
        match_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Match Score'
        },
        staged_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Title'
        },
        staged_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Description'
        },
        staged_meta: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Meta'
        },
        staged_images_json: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Images Json'
        },
        staged_weights_json: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Weights Json'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        attempt_count: {
            type: 'integer',
            title: 'Attempt Count'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'job_id',
        'tillin_product_id',
        'status',
        'attempt_count',
        'updated_at'
    ],
    title: 'ItemPublic'
} as const;

export const JobCountsSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total',
            default: 0
        },
        pending: {
            type: 'integer',
            title: 'Pending',
            default: 0
        },
        processing: {
            type: 'integer',
            title: 'Processing',
            default: 0
        },
        ready_for_review: {
            type: 'integer',
            title: 'Ready For Review',
            default: 0
        },
        approved: {
            type: 'integer',
            title: 'Approved',
            default: 0
        },
        applied: {
            type: 'integer',
            title: 'Applied',
            default: 0
        },
        rejected: {
            type: 'integer',
            title: 'Rejected',
            default: 0
        },
        failed: {
            type: 'integer',
            title: 'Failed',
            default: 0
        }
    },
    type: 'object',
    title: 'JobCounts'
} as const;

export const JobCreateRequestSchema = {
    properties: {
        selection: {
            $ref: '#/components/schemas/JobSelection'
        },
        config: {
            additionalProperties: true,
            type: 'object',
            title: 'Config'
        }
    },
    type: 'object',
    required: [
        'selection'
    ],
    title: 'JobCreateRequest'
} as const;

export const JobPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        selection_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Selection Json'
        },
        config_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Config Json'
        },
        counts: {
            $ref: '#/components/schemas/JobCounts'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'status',
        'selection_json',
        'config_json',
        'counts',
        'created_at'
    ],
    title: 'JobPublic'
} as const;

export const JobSelectionSchema = {
    properties: {
        ids: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ids'
        },
        tag: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tag'
        }
    },
    type: 'object',
    title: 'JobSelection',
    description: 'Product selection: explicit Tillin ids or a tag (exactly one).'
} as const;

export const LoginRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'LoginRequest',
    description: 'Credentials submitted to the login endpoint.'
} as const;

export const PaginatedResponse_ItemPublic_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages'
    ],
    title: 'PaginatedResponse[ItemPublic]'
} as const;

export const PaginatedResponse_JobPublic_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/JobPublic'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages'
    ],
    title: 'PaginatedResponse[JobPublic]'
} as const;

export const PaginatedResponse_Product_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/Product'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages'
    ],
    title: 'PaginatedResponse[Product]'
} as const;

export const ProductSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        reference_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reference Code'
        },
        brand: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Brand'
                },
                {
                    type: 'null'
                }
            ]
        },
        season: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Season'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        department: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        variants: {
            items: {
                $ref: '#/components/schemas/ProductVariant'
            },
            type: 'array',
            title: 'Variants'
        },
        images: {
            items: {
                $ref: '#/components/schemas/ProductImage'
            },
            type: 'array',
            title: 'Images'
        }
    },
    type: 'object',
    required: [
        'id'
    ],
    title: 'Product',
    description: 'Canonical product as consumed by the enrichment/intake engine.'
} as const;

export const ProductImageSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        position: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        }
    },
    type: 'object',
    required: [
        'url'
    ],
    title: 'ProductImage',
    description: 'An image associated with a product.'
} as const;

export const ProductVariantSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        sku: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        barcode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Barcode'
        },
        weight: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weight'
        },
        weight_unit: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weight Unit'
        }
    },
    type: 'object',
    title: 'ProductVariant',
    description: 'A single sellable variant (style x color x size) of a product.'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: [
        'id',
        'email',
        'is_active'
    ],
    title: 'UserPublic',
    description: 'Public-facing representation of a user.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const VersionResponseSchema = {
    properties: {
        app: {
            type: 'string',
            title: 'App'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        build: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Build'
        },
        commit: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Commit'
        },
        branch: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branch'
        },
        environment: {
            type: 'string',
            title: 'Environment'
        }
    },
    type: 'object',
    required: [
        'app',
        'version',
        'environment'
    ],
    title: 'VersionResponse',
    description: 'Response exposing the running application version metadata.'
} as const;
