// This file is auto-generated by @hey-api/openapi-ts

export const ExampleResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        sample_id: {
            type: 'integer',
            title: 'Sample Id'
        }
    },
    type: 'object',
    required: [
        'status',
        'message',
        'sample_id'
    ],
    title: 'ExampleResponse',
    description: 'Response payload returned by the example endpoint.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        status: {
            type: 'string',
            const: 'ok',
            title: 'Status'
        },
        database: {
            type: 'string',
            const: 'up',
            title: 'Database'
        }
    },
    type: 'object',
    required: [
        'status',
        'database'
    ],
    title: 'HealthResponse',
    description: 'Response returned by the healthcheck endpoint.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const VersionResponseSchema = {
    properties: {
        app: {
            type: 'string',
            title: 'App'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        build: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Build'
        },
        commit: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Commit'
        },
        branch: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branch'
        },
        environment: {
            type: 'string',
            title: 'Environment'
        }
    },
    type: 'object',
    required: [
        'app',
        'version',
        'environment'
    ],
    title: 'VersionResponse',
    description: 'Response exposing the running application version metadata.'
} as const;
