// This file is auto-generated by @hey-api/openapi-ts

export const AccountSettingsSchema = {
    properties: {
        title_template: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title Template'
        },
        title_case: {
            type: 'string',
            enum: [
                'none',
                'upper',
                'capitalize'
            ],
            title: 'Title Case',
            default: 'none'
        },
        editorial_instructions: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Editorial Instructions'
        },
        client_context: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Context'
        },
        meta_max_length: {
            type: 'integer',
            maximum: 320,
            minimum: 50,
            title: 'Meta Max Length',
            default: 160
        },
        notify_on_job_done: {
            type: 'boolean',
            title: 'Notify On Job Done',
            default: false
        },
        notify_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notify Email'
        },
        billing_coefficient: {
            type: 'number',
            minimum: 0,
            title: 'Billing Coefficient',
            default: 1
        },
        billing_day: {
            type: 'integer',
            maximum: 28,
            minimum: 1,
            title: 'Billing Day',
            default: 1
        }
    },
    type: 'object',
    title: 'AccountSettings',
    description: 'Boutique-level enrichment defaults (stored on account.settings_json).'
} as const;

export const AssetSaveRequestSchema = {
    properties: {
        replace: {
            type: 'boolean',
            title: 'Replace',
            default: false
        }
    },
    type: 'object',
    title: 'AssetSaveRequest',
    description: 'POST /imaging/assets/{id}/save body.'
} as const;

export const AssetSaveResultSchema = {
    properties: {
        created: {
            type: 'integer',
            title: 'Created'
        },
        deactivated: {
            type: 'integer',
            title: 'Deactivated'
        },
        images: {
            items: {
                $ref: '#/components/schemas/ProductImage'
            },
            type: 'array',
            title: 'Images'
        }
    },
    type: 'object',
    required: [
        'created',
        'deactivated'
    ],
    title: 'AssetSaveResult',
    description: 'Outcome of pushing a completed asset to Tillin (Xano bulk upload).'
} as const;

export const Body_imports_create_importSchema = {
    properties: {
        files: {
            items: {
                type: 'string',
                contentMediaType: 'application/octet-stream'
            },
            type: 'array',
            title: 'Files'
        },
        location_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        }
    },
    type: 'object',
    required: [
        'files'
    ],
    title: 'Body_imports-create_import'
} as const;

export const Body_products_upload_product_imagesSchema = {
    properties: {
        files: {
            items: {
                type: 'string',
                contentMediaType: 'application/octet-stream'
            },
            type: 'array',
            title: 'Files',
            description: 'Image files to upload'
        }
    },
    type: 'object',
    required: [
        'files'
    ],
    title: 'Body_products-upload_product_images'
} as const;

export const BrandSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        website_urls: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Website Urls'
        }
    },
    type: 'object',
    title: 'Brand',
    description: 'The brand a product belongs to, with its source website(s).'
} as const;

export const BrandPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        website_urls: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Website Urls'
        }
    },
    type: 'object',
    required: [
        'id'
    ],
    title: 'BrandPublic',
    description: 'A Tillin brand with its reference website URLs.'
} as const;

export const BrandWebsiteUrlsUpdateSchema = {
    properties: {
        website_urls: {
            items: {
                type: 'string',
                maxLength: 500
            },
            type: 'array',
            maxItems: 20,
            title: 'Website Urls'
        }
    },
    type: 'object',
    required: [
        'website_urls'
    ],
    title: 'BrandWebsiteUrlsUpdate',
    description: 'Replace a brand\'s reference website URLs.'
} as const;

export const CatalogFiltersSchema = {
    properties: {
        brands: {
            items: {
                $ref: '#/components/schemas/FilterOption'
            },
            type: 'array',
            title: 'Brands',
            default: []
        },
        categories: {
            items: {
                $ref: '#/components/schemas/FilterOption'
            },
            type: 'array',
            title: 'Categories',
            default: []
        },
        compositions: {
            items: {
                $ref: '#/components/schemas/FilterOption'
            },
            type: 'array',
            title: 'Compositions',
            default: []
        },
        seasons: {
            items: {
                $ref: '#/components/schemas/FilterOption'
            },
            type: 'array',
            title: 'Seasons',
            default: []
        },
        suppliers: {
            items: {
                $ref: '#/components/schemas/FilterOption'
            },
            type: 'array',
            title: 'Suppliers',
            default: []
        },
        tags: {
            items: {
                $ref: '#/components/schemas/FilterOption'
            },
            type: 'array',
            title: 'Tags',
            default: []
        }
    },
    type: 'object',
    title: 'CatalogFilters',
    description: 'Classification lists backing the product-search filters.'
} as const;

export const ConnectionStatusSchema = {
    properties: {
        configured: {
            type: 'boolean',
            title: 'Configured'
        },
        host: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Host'
        },
        data_source: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Source'
        }
    },
    type: 'object',
    required: [
        'configured'
    ],
    title: 'ConnectionStatus',
    description: 'Read-only Tillin/Xano connection health (no secrets).'
} as const;

export const DashboardStatsSchema = {
    properties: {
        applied_items: {
            type: 'integer',
            title: 'Applied Items',
            default: 0
        },
        ready_items: {
            type: 'integer',
            title: 'Ready Items',
            default: 0
        },
        running_jobs: {
            type: 'integer',
            title: 'Running Jobs',
            default: 0
        },
        jobs_total: {
            type: 'integer',
            title: 'Jobs Total',
            default: 0
        },
        items_total: {
            type: 'integer',
            title: 'Items Total',
            default: 0
        },
        avg_item_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Item Seconds'
        },
        auto_resolve_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Auto Resolve Rate'
        }
    },
    type: 'object',
    title: 'DashboardStats',
    description: 'Account-scoped headline numbers for the dashboard KPI row.'
} as const;

export const ExampleResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        sample_id: {
            type: 'integer',
            title: 'Sample Id'
        }
    },
    type: 'object',
    required: [
        'status',
        'message',
        'sample_id'
    ],
    title: 'ExampleResponse',
    description: 'Response payload returned by the example endpoint.'
} as const;

export const FilterOptionSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        }
    },
    type: 'object',
    required: [
        'id',
        'title'
    ],
    title: 'FilterOption',
    description: 'One selectable value in a search filter (brand, category, …).'
} as const;

export const GenerateModelOptionsSchema = {
    properties: {
        prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prompt',
            default: 'studio photo, plain light neutral background'
        },
        aspect_ratio: {
            type: 'string',
            title: 'Aspect Ratio',
            default: '4:5'
        },
        resolution: {
            type: 'string',
            enum: [
                '1k',
                '2k',
                '4k'
            ],
            title: 'Resolution',
            default: '1k'
        },
        generation_mode: {
            type: 'string',
            enum: [
                'fast',
                'balanced',
                'quality'
            ],
            title: 'Generation Mode',
            default: 'balanced'
        },
        seed: {
            type: 'integer',
            title: 'Seed',
            default: 42
        },
        num_images: {
            type: 'integer',
            maximum: 4,
            minimum: 1,
            title: 'Num Images',
            default: 1
        }
    },
    type: 'object',
    title: 'GenerateModelOptions',
    description: 'Options of POST /products/{id}/images/generate-model (FASHN).'
} as const;

export const GenerateModelRequestSchema = {
    properties: {
        image_url: {
            type: 'string',
            title: 'Image Url'
        },
        product_image_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Image Id'
        },
        options: {
            anyOf: [
                {
                    $ref: '#/components/schemas/GenerateModelOptions'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'image_url'
    ],
    title: 'GenerateModelRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        status: {
            type: 'string',
            const: 'ok',
            title: 'Status'
        },
        database: {
            type: 'string',
            const: 'up',
            title: 'Database'
        }
    },
    type: 'object',
    required: [
        'status',
        'database'
    ],
    title: 'HealthResponse',
    description: 'Response returned by the healthcheck endpoint.'
} as const;

export const ImageAssetPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        product_id: {
            type: 'integer',
            title: 'Product Id'
        },
        verb: {
            type: 'string',
            title: 'Verb'
        },
        provider: {
            type: 'string',
            title: 'Provider'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        seed: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seed'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        preview_urls: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Preview Urls'
        },
        source_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Image'
        },
        source_product_image_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Product Image Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        }
    },
    type: 'object',
    required: [
        'id',
        'product_id',
        'verb',
        'provider',
        'status',
        'created_at'
    ],
    title: 'ImageAssetPublic',
    description: 'One imaging operation: status + provenance + staged previews.'
} as const;

export const ImportFilePreviewSchema = {
    properties: {
        kind: {
            type: 'string',
            enum: [
                'pdf',
                'tabular'
            ],
            title: 'Kind'
        },
        file_name: {
            type: 'string',
            title: 'File Name'
        },
        sheets: {
            items: {
                $ref: '#/components/schemas/ImportFilePreviewSheet'
            },
            type: 'array',
            title: 'Sheets'
        }
    },
    type: 'object',
    required: [
        'kind',
        'file_name'
    ],
    title: 'ImportFilePreview'
} as const;

export const ImportFilePreviewSheetSchema = {
    properties: {
        sheet: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sheet'
        },
        rows: {
            items: {
                items: {
                    type: 'string'
                },
                type: 'array'
            },
            type: 'array',
            title: 'Rows'
        },
        total_rows: {
            type: 'integer',
            title: 'Total Rows',
            default: 0
        },
        truncated: {
            type: 'boolean',
            title: 'Truncated',
            default: false
        }
    },
    type: 'object',
    title: 'ImportFilePreviewSheet'
} as const;

export const ImportItemPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        tillin_product_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tillin Product Id'
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload'
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'status',
        'payload',
        'created_at'
    ],
    title: 'ImportItemPublic'
} as const;

export const ImportItemUpdateSchema = {
    properties: {
        payload: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payload'
        },
        status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        }
    },
    type: 'object',
    title: 'ImportItemUpdate',
    description: 'Review edits: a corrected payload and/or a reject/restore status.'
} as const;

export const ImportJobCountsSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total',
            default: 0
        },
        ready_for_review: {
            type: 'integer',
            title: 'Ready For Review',
            default: 0
        },
        applied: {
            type: 'integer',
            title: 'Applied',
            default: 0
        },
        rejected: {
            type: 'integer',
            title: 'Rejected',
            default: 0
        },
        failed: {
            type: 'integer',
            title: 'Failed',
            default: 0
        }
    },
    type: 'object',
    title: 'ImportJobCounts'
} as const;

export const ImportJobPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        file_name: {
            type: 'string',
            title: 'File Name'
        },
        file_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'File Names'
        },
        counts: {
            $ref: '#/components/schemas/ImportJobCounts'
        },
        totals: {
            $ref: '#/components/schemas/ImportJobTotals'
        },
        po_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Po Number'
        },
        supplier: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supplier'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        location_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location Id'
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        }
    },
    type: 'object',
    required: [
        'id',
        'status',
        'file_name',
        'counts',
        'created_at'
    ],
    title: 'ImportJobPublic'
} as const;

export const ImportJobTotalsSchema = {
    properties: {
        quantity: {
            type: 'integer',
            title: 'Quantity',
            default: 0
        },
        wholesale_amount: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Wholesale Amount'
        },
        retail_amount: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Retail Amount'
        }
    },
    type: 'object',
    title: 'ImportJobTotals',
    description: 'Aggregates over every extracted variant (a missing quantity counts\nas 1 unit; amounts are quantity x unit price, None when no price at all).'
} as const;

export const ImportLinkResultSchema = {
    properties: {
        linked: {
            type: 'integer',
            title: 'Linked',
            default: 0
        },
        already_linked: {
            type: 'integer',
            title: 'Already Linked',
            default: 0
        },
        not_found: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Not Found'
        }
    },
    type: 'object',
    title: 'ImportLinkResult',
    description: 'POST /imports/{id}/link-products outcome (resolution by reference).'
} as const;

export const ImportLocationSelectionSchema = {
    properties: {
        location_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location Id'
        }
    },
    type: 'object',
    required: [
        'location_id'
    ],
    title: 'ImportLocationSelection',
    description: 'PUT /imports/{id}/location body — null clears the selection.'
} as const;

export const ImportProductLineSchema = {
    properties: {
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        supplier_ref: {
            type: 'string',
            title: 'Supplier Ref'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        brand: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        variant_count: {
            type: 'integer',
            title: 'Variant Count',
            default: 0
        },
        tillin_product_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tillin Product Id'
        }
    },
    type: 'object',
    required: [
        'item_id',
        'status',
        'supplier_ref'
    ],
    title: 'ImportProductLine',
    description: 'One row of the « Par import » products view (local data only).'
} as const;

export const ImportProductsSchema = {
    properties: {
        import_id: {
            type: 'integer',
            title: 'Import Id'
        },
        file_name: {
            type: 'string',
            title: 'File Name'
        },
        items: {
            items: {
                $ref: '#/components/schemas/ImportProductLine'
            },
            type: 'array',
            title: 'Items'
        },
        linked_count: {
            type: 'integer',
            title: 'Linked Count',
            default: 0
        },
        unlinked_count: {
            type: 'integer',
            title: 'Unlinked Count',
            default: 0
        }
    },
    type: 'object',
    required: [
        'import_id',
        'file_name'
    ],
    title: 'ImportProducts'
} as const;

export const ImportProfileConfig_InputSchema = {
    properties: {
        price_mode: {
            type: 'string',
            enum: [
                'retail_as_is',
                'coefficient'
            ],
            title: 'Price Mode',
            default: 'retail_as_is'
        },
        coefficient: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Coefficient'
        },
        round_up_to: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Round Up To',
            default: '5'
        },
        barcode_mode: {
            type: 'string',
            enum: [
                'ean',
                'constructed'
            ],
            title: 'Barcode Mode',
            default: 'ean'
        },
        brand_mode: {
            type: 'string',
            enum: [
                'as_extracted',
                'fixed'
            ],
            title: 'Brand Mode',
            default: 'as_extracted'
        },
        brand_value: {
            type: 'string',
            title: 'Brand Value',
            default: ''
        },
        supplier_label: {
            type: 'string',
            title: 'Supplier Label',
            default: ''
        },
        season_label: {
            type: 'string',
            title: 'Season Label',
            default: ''
        },
        tax_rate: {
            type: 'string',
            title: 'Tax Rate',
            default: '20'
        },
        wholesale_tax_rate: {
            type: 'string',
            title: 'Wholesale Tax Rate',
            default: '20'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'active'
        },
        apply_title_template: {
            type: 'boolean',
            title: 'Apply Title Template',
            default: false
        }
    },
    type: 'object',
    title: 'ImportProfileConfig',
    description: 'Frozen convention shapes; every field has a safe default.'
} as const;

export const ImportProfileConfig_OutputSchema = {
    properties: {
        price_mode: {
            type: 'string',
            enum: [
                'retail_as_is',
                'coefficient'
            ],
            title: 'Price Mode',
            default: 'retail_as_is'
        },
        coefficient: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Coefficient'
        },
        round_up_to: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Round Up To',
            default: '5'
        },
        barcode_mode: {
            type: 'string',
            enum: [
                'ean',
                'constructed'
            ],
            title: 'Barcode Mode',
            default: 'ean'
        },
        brand_mode: {
            type: 'string',
            enum: [
                'as_extracted',
                'fixed'
            ],
            title: 'Brand Mode',
            default: 'as_extracted'
        },
        brand_value: {
            type: 'string',
            title: 'Brand Value',
            default: ''
        },
        supplier_label: {
            type: 'string',
            title: 'Supplier Label',
            default: ''
        },
        season_label: {
            type: 'string',
            title: 'Season Label',
            default: ''
        },
        tax_rate: {
            type: 'string',
            title: 'Tax Rate',
            default: '20'
        },
        wholesale_tax_rate: {
            type: 'string',
            title: 'Wholesale Tax Rate',
            default: '20'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'active'
        },
        apply_title_template: {
            type: 'boolean',
            title: 'Apply Title Template',
            default: false
        }
    },
    type: 'object',
    title: 'ImportProfileConfig',
    description: 'Frozen convention shapes; every field has a safe default.'
} as const;

export const ImportProfileCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 120,
            minLength: 1,
            title: 'Name'
        },
        supplier_match: {
            type: 'string',
            maxLength: 120,
            title: 'Supplier Match',
            default: ''
        },
        config: {
            $ref: '#/components/schemas/ImportProfileConfig-Input'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'ImportProfileCreate'
} as const;

export const ImportProfilePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        supplier_match: {
            type: 'string',
            title: 'Supplier Match'
        },
        config: {
            $ref: '#/components/schemas/ImportProfileConfig-Output'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'supplier_match',
        'config',
        'created_at',
        'updated_at'
    ],
    title: 'ImportProfilePublic'
} as const;

export const ImportProfileSelectionSchema = {
    properties: {
        profile_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        }
    },
    type: 'object',
    required: [
        'profile_id'
    ],
    title: 'ImportProfileSelection',
    description: 'PUT /imports/{id}/profile body — null clears the selection.'
} as const;

export const ImportProfileUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 120,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        supplier_match: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 120
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supplier Match'
        },
        config: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ImportProfileConfig-Input'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'ImportProfileUpdate'
} as const;

export const ImportRenderPreviewSchema = {
    properties: {
        columns: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Columns'
        },
        rows: {
            items: {
                items: {
                    type: 'string'
                },
                type: 'array'
            },
            type: 'array',
            title: 'Rows'
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings'
        },
        row_count: {
            type: 'integer',
            title: 'Row Count',
            default: 0
        }
    },
    type: 'object',
    required: [
        'columns',
        'rows'
    ],
    title: 'ImportRenderPreview',
    description: 'JSON preview of the rendered Tillin import CSV.'
} as const;

export const ImportTransferRequestSchema = {
    properties: {
        location_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        }
    },
    type: 'object',
    title: 'ImportTransferRequest',
    description: 'POST /imports/{id}/transfer body.\n\nA null location falls back to the job\'s selected location\n(config_json["location_id"]); missing both is a 400 `location_required`.'
} as const;

export const ImportTransferResultSchema = {
    properties: {
        ok: {
            type: 'boolean',
            title: 'Ok',
            default: true
        },
        row_count: {
            type: 'integer',
            title: 'Row Count',
            default: 0
        }
    },
    type: 'object',
    title: 'ImportTransferResult'
} as const;

export const InstructionCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 120,
            minLength: 1,
            title: 'Name'
        },
        content: {
            type: 'string',
            minLength: 1,
            title: 'Content'
        },
        categories: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Categories'
        }
    },
    type: 'object',
    required: [
        'name',
        'content'
    ],
    title: 'InstructionCreate'
} as const;

export const InstructionPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        categories: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Categories'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'content',
        'created_at',
        'updated_at'
    ],
    title: 'InstructionPublic'
} as const;

export const InstructionUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 120,
            minLength: 1,
            title: 'Name'
        },
        content: {
            type: 'string',
            minLength: 1,
            title: 'Content'
        },
        categories: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Categories'
        }
    },
    type: 'object',
    required: [
        'name',
        'content'
    ],
    title: 'InstructionUpdate'
} as const;

export const ItemImageNormalizeRequestSchema = {
    properties: {
        url: {
            type: 'string',
            minLength: 1,
            title: 'Url'
        },
        revert: {
            type: 'boolean',
            title: 'Revert',
            default: false
        }
    },
    type: 'object',
    required: [
        'url'
    ],
    title: 'ItemImageNormalizeRequest',
    description: 'Per-image review action: normalize one staged image (or revert it).'
} as const;

export const ItemPatchRequestSchema = {
    properties: {
        staged_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Title'
        },
        staged_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Description'
        },
        staged_meta: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Meta'
        },
        staged_images_json: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Images Json'
        },
        staged_weights_json: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Weights Json'
        },
        apply_fields_json: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Apply Fields Json'
        }
    },
    type: 'object',
    title: 'ItemPatchRequest',
    description: 'Editable staged fields (review-time corrections).'
} as const;

export const ItemPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        job_id: {
            type: 'integer',
            title: 'Job Id'
        },
        tillin_product_id: {
            type: 'integer',
            title: 'Tillin Product Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        source_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Url'
        },
        source_method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Method'
        },
        match_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Match Score'
        },
        resolution_json: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolution Json'
        },
        staged_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Title'
        },
        staged_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Description'
        },
        staged_meta: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Meta'
        },
        staged_images_json: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Images Json'
        },
        staged_weights_json: {
            anyOf: [
                {
                    items: {},
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Staged Weights Json'
        },
        apply_fields_json: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Apply Fields Json'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        attempt_count: {
            type: 'integer',
            title: 'Attempt Count'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'job_id',
        'tillin_product_id',
        'status',
        'attempt_count',
        'updated_at'
    ],
    title: 'ItemPublic'
} as const;

export const ItemResolveRequestSchema = {
    properties: {
        source_url: {
            type: 'string',
            minLength: 1,
            title: 'Source Url'
        }
    },
    type: 'object',
    required: [
        'source_url'
    ],
    title: 'ItemResolveRequest',
    description: 'Manually point an item at a specific source product page.\n\nAny http(s) URL is accepted since the Firecrawl fallback: non-Shopify\npages go through LLM extraction (the old validator required a Shopify\n`/products/` URL and would have blocked e.g. salomon.com in the review).'
} as const;

export const JobCountsSchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total',
            default: 0
        },
        pending: {
            type: 'integer',
            title: 'Pending',
            default: 0
        },
        processing: {
            type: 'integer',
            title: 'Processing',
            default: 0
        },
        ready_for_review: {
            type: 'integer',
            title: 'Ready For Review',
            default: 0
        },
        approved: {
            type: 'integer',
            title: 'Approved',
            default: 0
        },
        applied: {
            type: 'integer',
            title: 'Applied',
            default: 0
        },
        rejected: {
            type: 'integer',
            title: 'Rejected',
            default: 0
        },
        failed: {
            type: 'integer',
            title: 'Failed',
            default: 0
        }
    },
    type: 'object',
    title: 'JobCounts'
} as const;

export const JobCreateRequestSchema = {
    properties: {
        selection: {
            $ref: '#/components/schemas/JobSelection'
        },
        config: {
            additionalProperties: true,
            type: 'object',
            title: 'Config'
        }
    },
    type: 'object',
    required: [
        'selection'
    ],
    title: 'JobCreateRequest'
} as const;

export const JobPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        selection_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Selection Json'
        },
        config_json: {
            additionalProperties: true,
            type: 'object',
            title: 'Config Json'
        },
        counts: {
            $ref: '#/components/schemas/JobCounts'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        }
    },
    type: 'object',
    required: [
        'id',
        'status',
        'selection_json',
        'config_json',
        'counts',
        'created_at'
    ],
    title: 'JobPublic'
} as const;

export const JobSelectionSchema = {
    properties: {
        ids: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ids'
        },
        tag: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tag'
        }
    },
    type: 'object',
    title: 'JobSelection',
    description: 'Product selection: explicit Tillin ids or a tag (exactly one).'
} as const;

export const LocationPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        }
    },
    type: 'object',
    required: [
        'id',
        'title'
    ],
    title: 'LocationPublic',
    description: 'A Tillin boutique location a CSV import can be transferred to.'
} as const;

export const LoginRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'LoginRequest',
    description: 'Credentials submitted to the login endpoint.'
} as const;

export const NormalizeOptionsSchema = {
    properties: {
        bg_color: {
            type: 'string',
            title: 'Bg Color',
            default: 'FFFFFF'
        },
        output_size: {
            type: 'string',
            title: 'Output Size',
            default: '1600x2000'
        },
        padding: {
            type: 'string',
            title: 'Padding',
            default: '10%'
        },
        format: {
            type: 'string',
            title: 'Format',
            default: 'webp'
        },
        quality: {
            type: 'integer',
            maximum: 100,
            minimum: 1,
            title: 'Quality',
            default: 80
        },
        max_kb: {
            type: 'integer',
            minimum: 1,
            title: 'Max Kb',
            default: 200
        }
    },
    type: 'object',
    title: 'NormalizeOptions',
    description: 'Options of POST /products/{id}/images/normalize (Photoroom).'
} as const;

export const NormalizeRequestSchema = {
    properties: {
        image_url: {
            type: 'string',
            title: 'Image Url'
        },
        product_image_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Image Id'
        },
        options: {
            anyOf: [
                {
                    $ref: '#/components/schemas/NormalizeOptions'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'image_url'
    ],
    title: 'NormalizeRequest'
} as const;

export const PaginatedResponse_ImportItemPublic_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/ImportItemPublic'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages'
    ],
    title: 'PaginatedResponse[ImportItemPublic]'
} as const;

export const PaginatedResponse_ImportJobPublic_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/ImportJobPublic'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages'
    ],
    title: 'PaginatedResponse[ImportJobPublic]'
} as const;

export const PaginatedResponse_ItemPublic_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages'
    ],
    title: 'PaginatedResponse[ItemPublic]'
} as const;

export const PaginatedResponse_JobPublic_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/JobPublic'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages'
    ],
    title: 'PaginatedResponse[JobPublic]'
} as const;

export const PaginatedResponse_Product_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/Product'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page'
        },
        page_size: {
            type: 'integer',
            title: 'Page Size'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size',
        'total_pages'
    ],
    title: 'PaginatedResponse[Product]'
} as const;

export const PasswordChangeRequestSchema = {
    properties: {
        current_password: {
            type: 'string',
            minLength: 1,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'current_password',
        'new_password'
    ],
    title: 'PasswordChangeRequest'
} as const;

export const ProductSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        reference_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reference Code'
        },
        brand: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Brand'
                },
                {
                    type: 'null'
                }
            ]
        },
        season: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Season'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        department: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        composition: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Composition'
        },
        manufacturing_country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Manufacturing Country'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        meta_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Meta Description'
        },
        price: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        variants: {
            items: {
                $ref: '#/components/schemas/ProductVariant'
            },
            type: 'array',
            title: 'Variants'
        },
        images: {
            items: {
                $ref: '#/components/schemas/ProductImage'
            },
            type: 'array',
            title: 'Images'
        }
    },
    type: 'object',
    required: [
        'id'
    ],
    title: 'Product',
    description: 'Canonical product as consumed by the enrichment/intake engine.'
} as const;

export const ProductImageSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        position: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        }
    },
    type: 'object',
    required: [
        'url'
    ],
    title: 'ProductImage',
    description: 'An image associated with a product.'
} as const;

export const ProductImagesUploadResultSchema = {
    properties: {
        created: {
            type: 'integer',
            title: 'Created'
        },
        images: {
            items: {
                $ref: '#/components/schemas/ProductImage'
            },
            type: 'array',
            title: 'Images'
        }
    },
    type: 'object',
    required: [
        'created'
    ],
    title: 'ProductImagesUploadResult',
    description: 'Outcome of uploading images to a product: the newly created images.'
} as const;

export const ProductVariantSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        sku: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        barcode: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Barcode'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        size: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size'
        },
        weight: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weight'
        },
        weight_unit: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weight Unit'
        },
        price: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        wholesale_price: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Wholesale Price'
        }
    },
    type: 'object',
    title: 'ProductVariant',
    description: 'A single sellable variant (style x color x size) of a product.'
} as const;

export const UsageByJobSchema = {
    properties: {
        month: {
            type: 'string',
            title: 'Month'
        },
        jobs: {
            items: {
                $ref: '#/components/schemas/UsageJobLine'
            },
            type: 'array',
            title: 'Jobs'
        }
    },
    type: 'object',
    required: [
        'month',
        'jobs'
    ],
    title: 'UsageByJob'
} as const;

export const UsageJobLineSchema = {
    properties: {
        job_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Id'
        },
        job_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Type'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        input_tokens: {
            type: 'integer',
            title: 'Input Tokens'
        },
        output_tokens: {
            type: 'integer',
            title: 'Output Tokens'
        },
        other_metrics: {
            items: {
                $ref: '#/components/schemas/UsageJobMetric'
            },
            type: 'array',
            title: 'Other Metrics'
        },
        cost: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cost'
        },
        billable: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Billable'
        }
    },
    type: 'object',
    required: [
        'job_id',
        'job_type',
        'label',
        'created_at',
        'input_tokens',
        'output_tokens',
        'other_metrics',
        'cost',
        'billable'
    ],
    title: 'UsageJobLine'
} as const;

export const UsageJobMetricSchema = {
    properties: {
        provider: {
            type: 'string',
            title: 'Provider'
        },
        metric: {
            type: 'string',
            title: 'Metric'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        }
    },
    type: 'object',
    required: [
        'provider',
        'metric',
        'quantity'
    ],
    title: 'UsageJobMetric'
} as const;

export const UsagePriceCreateSchema = {
    properties: {
        provider: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Provider'
        },
        model: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 80
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        metric: {
            type: 'string',
            maxLength: 30,
            minLength: 1,
            title: 'Metric'
        },
        unit_price: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Unit Price'
        },
        currency: {
            type: 'string',
            maxLength: 3,
            minLength: 3,
            title: 'Currency',
            default: 'EUR'
        }
    },
    type: 'object',
    required: [
        'provider',
        'metric',
        'unit_price'
    ],
    title: 'UsagePriceCreate'
} as const;

export const UsagePricePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        provider: {
            type: 'string',
            title: 'Provider'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        metric: {
            type: 'string',
            title: 'Metric'
        },
        unit_price: {
            type: 'string',
            title: 'Unit Price'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        }
    },
    type: 'object',
    required: [
        'id',
        'provider',
        'model',
        'metric',
        'unit_price',
        'currency'
    ],
    title: 'UsagePricePublic'
} as const;

export const UsagePriceUpdateSchema = {
    properties: {
        provider: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider'
        },
        model: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 80
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        metric: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metric'
        },
        unit_price: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Price'
        },
        currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3,
                    minLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        }
    },
    type: 'object',
    title: 'UsagePriceUpdate'
} as const;

export const UsageSummarySchema = {
    properties: {
        month: {
            type: 'string',
            title: 'Month'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        coefficient: {
            type: 'number',
            title: 'Coefficient'
        },
        lines: {
            items: {
                $ref: '#/components/schemas/UsageSummaryLine'
            },
            type: 'array',
            title: 'Lines'
        },
        totals: {
            $ref: '#/components/schemas/UsageTotals'
        },
        unpriced_count: {
            type: 'integer',
            title: 'Unpriced Count'
        },
        frozen: {
            type: 'boolean',
            title: 'Frozen',
            default: false
        },
        billing_date: {
            type: 'string',
            title: 'Billing Date'
        },
        frozen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Frozen At'
        }
    },
    type: 'object',
    required: [
        'month',
        'currency',
        'coefficient',
        'lines',
        'totals',
        'unpriced_count',
        'billing_date'
    ],
    title: 'UsageSummary'
} as const;

export const UsageSummaryLineSchema = {
    properties: {
        provider: {
            type: 'string',
            title: 'Provider'
        },
        model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model'
        },
        metric: {
            type: 'string',
            title: 'Metric'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        },
        unit_price: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Price'
        },
        cost: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cost'
        },
        billable: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Billable'
        }
    },
    type: 'object',
    required: [
        'provider',
        'model',
        'metric',
        'quantity',
        'unit_price',
        'cost',
        'billable'
    ],
    title: 'UsageSummaryLine'
} as const;

export const UsageTimeseriesSchema = {
    properties: {
        month: {
            type: 'string',
            title: 'Month'
        },
        group_by: {
            type: 'string',
            title: 'Group By'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        series: {
            items: {
                $ref: '#/components/schemas/UsageTimeseriesSeries'
            },
            type: 'array',
            title: 'Series'
        }
    },
    type: 'object',
    required: [
        'month',
        'group_by',
        'currency',
        'series'
    ],
    title: 'UsageTimeseries'
} as const;

export const UsageTimeseriesPointSchema = {
    properties: {
        date: {
            type: 'string',
            title: 'Date'
        },
        amount: {
            type: 'string',
            title: 'Amount'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        }
    },
    type: 'object',
    required: [
        'date',
        'amount',
        'quantity'
    ],
    title: 'UsageTimeseriesPoint'
} as const;

export const UsageTimeseriesSeriesSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        points: {
            items: {
                $ref: '#/components/schemas/UsageTimeseriesPoint'
            },
            type: 'array',
            title: 'Points'
        }
    },
    type: 'object',
    required: [
        'key',
        'points'
    ],
    title: 'UsageTimeseriesSeries'
} as const;

export const UsageTotalsSchema = {
    properties: {
        cost: {
            type: 'string',
            title: 'Cost'
        },
        billable: {
            type: 'string',
            title: 'Billable'
        }
    },
    type: 'object',
    required: [
        'cost',
        'billable'
    ],
    title: 'UsageTotals'
} as const;

export const UserPreferencesSchema = {
    properties: {
        shortcuts_enabled: {
            type: 'boolean',
            title: 'Shortcuts Enabled',
            default: false
        },
        auto_advance: {
            type: 'boolean',
            title: 'Auto Advance',
            default: true
        },
        density: {
            type: 'string',
            enum: [
                'comfortable',
                'compact'
            ],
            title: 'Density',
            default: 'comfortable'
        },
        products_per_page: {
            type: 'integer',
            maximum: 100,
            minimum: 10,
            title: 'Products Per Page',
            default: 20
        }
    },
    type: 'object',
    title: 'UserPreferences',
    description: 'Per-user UI preferences (stored on user.preferences_json).\n\nUnknown keys in storage are ignored; missing keys take these defaults.'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: [
        'id',
        'email',
        'is_active'
    ],
    title: 'UserPublic',
    description: 'Public-facing representation of a user.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const VersionResponseSchema = {
    properties: {
        app: {
            type: 'string',
            title: 'App'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        build: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Build'
        },
        commit: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Commit'
        },
        branch: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branch'
        },
        environment: {
            type: 'string',
            title: 'Environment'
        }
    },
    type: 'object',
    required: [
        'app',
        'version',
        'environment'
    ],
    title: 'VersionResponse',
    description: 'Response exposing the running application version metadata.'
} as const;
