// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthLoginData, AuthLoginErrors, AuthLoginResponses, AuthLogoutData, AuthLogoutResponses, AuthReadCurrentUserData, AuthReadCurrentUserErrors, AuthReadCurrentUserResponses, CatalogGetFiltersData, CatalogGetFiltersErrors, CatalogGetFiltersResponses, ExampleReadExampleData, ExampleReadExampleErrors, ExampleReadExampleResponses, ItemsApplyItemRouteData, ItemsApplyItemRouteErrors, ItemsApplyItemRouteResponses, ItemsApproveItemData, ItemsApproveItemErrors, ItemsApproveItemResponses, ItemsPatchItemData, ItemsPatchItemErrors, ItemsPatchItemResponses, ItemsReadItemData, ItemsReadItemErrors, ItemsReadItemProductData, ItemsReadItemProductErrors, ItemsReadItemProductResponses, ItemsReadItemResponses, ItemsRejectItemData, ItemsRejectItemErrors, ItemsRejectItemResponses, ItemsResolveItemRouteData, ItemsResolveItemRouteErrors, ItemsResolveItemRouteResponses, ItemsRetryItemRouteData, ItemsRetryItemRouteErrors, ItemsRetryItemRouteResponses, JobsCreateEnrichmentJobData, JobsCreateEnrichmentJobErrors, JobsCreateEnrichmentJobResponses, JobsListJobItemsData, JobsListJobItemsErrors, JobsListJobItemsResponses, JobsListJobsData, JobsListJobsErrors, JobsListJobsResponses, JobsReadJobData, JobsReadJobErrors, JobsReadJobResponses, JobsRetryJobFailuresData, JobsRetryJobFailuresErrors, JobsRetryJobFailuresResponses, ProductsListProductsData, ProductsListProductsErrors, ProductsListProductsResponses, SystemHealthcheckData, SystemHealthcheckResponses, SystemVersionData, SystemVersionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Healthcheck
 *
 * Return backend health only when PostgreSQL is reachable.
 */
export const systemHealthcheck = <ThrowOnError extends boolean = false>(options?: Options<SystemHealthcheckData, ThrowOnError>): RequestResult<SystemHealthcheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<SystemHealthcheckResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/healthcheck',
    ...options
});

/**
 * Version
 *
 * Return application version and runtime metadata.
 */
export const systemVersion = <ThrowOnError extends boolean = false>(options?: Options<SystemVersionData, ThrowOnError>): RequestResult<SystemVersionResponses, unknown, ThrowOnError> => (options?.client ?? client).get<SystemVersionResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/version',
    ...options
});

/**
 * Read Example
 *
 * Return a small payload without touching the database.
 */
export const exampleReadExample = <ThrowOnError extends boolean = false>(options?: Options<ExampleReadExampleData, ThrowOnError>): RequestResult<ExampleReadExampleResponses, ExampleReadExampleErrors, ThrowOnError> => (options?.client ?? client).get<ExampleReadExampleResponses, ExampleReadExampleErrors, ThrowOnError>({
    responseType: 'json',
    url: '/example',
    ...options
});

/**
 * Login
 *
 * Verify credentials and set the session cookie.
 *
 * Tries app-local users first, then falls back to Xano credentials so Tillin
 * users can sign in with their Xano identifiers.
 */
export const authLogin = <ThrowOnError extends boolean = false>(options: Options<AuthLoginData, ThrowOnError>): RequestResult<AuthLoginResponses, AuthLoginErrors, ThrowOnError> => (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 *
 * Clear the session cookie.
 */
export const authLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthLogoutData, ThrowOnError>): RequestResult<AuthLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<AuthLogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });

/**
 * Read Current User
 *
 * Return the currently authenticated user.
 */
export const authReadCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<AuthReadCurrentUserData, ThrowOnError>): RequestResult<AuthReadCurrentUserResponses, AuthReadCurrentUserErrors, ThrowOnError> => (options?.client ?? client).get<AuthReadCurrentUserResponses, AuthReadCurrentUserErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/me',
    ...options
});

/**
 * List Products
 *
 * Return a page of canonical products matching the search + filters.
 */
export const productsListProducts = <ThrowOnError extends boolean = false>(options?: Options<ProductsListProductsData, ThrowOnError>): RequestResult<ProductsListProductsResponses, ProductsListProductsErrors, ThrowOnError> => (options?.client ?? client).get<ProductsListProductsResponses, ProductsListProductsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/products',
    ...options
});

/**
 * Get Filters
 *
 * Brands, categories, seasons, suppliers and tags for the search filters.
 */
export const catalogGetFilters = <ThrowOnError extends boolean = false>(options?: Options<CatalogGetFiltersData, ThrowOnError>): RequestResult<CatalogGetFiltersResponses, CatalogGetFiltersErrors, ThrowOnError> => (options?.client ?? client).get<CatalogGetFiltersResponses, CatalogGetFiltersErrors, ThrowOnError>({
    responseType: 'json',
    url: '/catalog/filters',
    ...options
});

/**
 * List Jobs
 */
export const jobsListJobs = <ThrowOnError extends boolean = false>(options?: Options<JobsListJobsData, ThrowOnError>): RequestResult<JobsListJobsResponses, JobsListJobsErrors, ThrowOnError> => (options?.client ?? client).get<JobsListJobsResponses, JobsListJobsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/jobs',
    ...options
});

/**
 * Create Enrichment Job
 *
 * Create a job, enqueue its items, and kick off processing in the
 * background (the response returns at once; the worker drains after).
 */
export const jobsCreateEnrichmentJob = <ThrowOnError extends boolean = false>(options: Options<JobsCreateEnrichmentJobData, ThrowOnError>): RequestResult<JobsCreateEnrichmentJobResponses, JobsCreateEnrichmentJobErrors, ThrowOnError> => (options.client ?? client).post<JobsCreateEnrichmentJobResponses, JobsCreateEnrichmentJobErrors, ThrowOnError>({
    responseType: 'json',
    url: '/jobs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retry Job Failures
 *
 * Requeue a job's failed/rejected items and kick the worker.
 */
export const jobsRetryJobFailures = <ThrowOnError extends boolean = false>(options: Options<JobsRetryJobFailuresData, ThrowOnError>): RequestResult<JobsRetryJobFailuresResponses, JobsRetryJobFailuresErrors, ThrowOnError> => (options.client ?? client).post<JobsRetryJobFailuresResponses, JobsRetryJobFailuresErrors, ThrowOnError>({
    responseType: 'json',
    url: '/jobs/{job_id}/retry',
    ...options
});

/**
 * Read Job
 */
export const jobsReadJob = <ThrowOnError extends boolean = false>(options: Options<JobsReadJobData, ThrowOnError>): RequestResult<JobsReadJobResponses, JobsReadJobErrors, ThrowOnError> => (options.client ?? client).get<JobsReadJobResponses, JobsReadJobErrors, ThrowOnError>({
    responseType: 'json',
    url: '/jobs/{job_id}',
    ...options
});

/**
 * List Job Items
 *
 * List a job's items, optionally filtered by status (review queue).
 */
export const jobsListJobItems = <ThrowOnError extends boolean = false>(options: Options<JobsListJobItemsData, ThrowOnError>): RequestResult<JobsListJobItemsResponses, JobsListJobItemsErrors, ThrowOnError> => (options.client ?? client).get<JobsListJobItemsResponses, JobsListJobItemsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/jobs/{job_id}/items',
    ...options
});

/**
 * Read Item
 */
export const itemsReadItem = <ThrowOnError extends boolean = false>(options: Options<ItemsReadItemData, ThrowOnError>): RequestResult<ItemsReadItemResponses, ItemsReadItemErrors, ThrowOnError> => (options.client ?? client).get<ItemsReadItemResponses, ItemsReadItemErrors, ThrowOnError>({
    responseType: 'json',
    url: '/items/{item_id}',
    ...options
});

/**
 * Patch Item
 */
export const itemsPatchItem = <ThrowOnError extends boolean = false>(options: Options<ItemsPatchItemData, ThrowOnError>): RequestResult<ItemsPatchItemResponses, ItemsPatchItemErrors, ThrowOnError> => (options.client ?? client).patch<ItemsPatchItemResponses, ItemsPatchItemErrors, ThrowOnError>({
    responseType: 'json',
    url: '/items/{item_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Item Product
 *
 * Fetch the item's current Tillin product (before/after review context).
 */
export const itemsReadItemProduct = <ThrowOnError extends boolean = false>(options: Options<ItemsReadItemProductData, ThrowOnError>): RequestResult<ItemsReadItemProductResponses, ItemsReadItemProductErrors, ThrowOnError> => (options.client ?? client).get<ItemsReadItemProductResponses, ItemsReadItemProductErrors, ThrowOnError>({
    responseType: 'json',
    url: '/items/{item_id}/product',
    ...options
});

/**
 * Resolve Item Route
 *
 * Manually resolve an item from a chosen source page and re-stage it.
 */
export const itemsResolveItemRoute = <ThrowOnError extends boolean = false>(options: Options<ItemsResolveItemRouteData, ThrowOnError>): RequestResult<ItemsResolveItemRouteResponses, ItemsResolveItemRouteErrors, ThrowOnError> => (options.client ?? client).post<ItemsResolveItemRouteResponses, ItemsResolveItemRouteErrors, ThrowOnError>({
    responseType: 'json',
    url: '/items/{item_id}/resolve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retry Item Route
 *
 * Requeue one item for a full re-generation and kick the worker.
 */
export const itemsRetryItemRoute = <ThrowOnError extends boolean = false>(options: Options<ItemsRetryItemRouteData, ThrowOnError>): RequestResult<ItemsRetryItemRouteResponses, ItemsRetryItemRouteErrors, ThrowOnError> => (options.client ?? client).post<ItemsRetryItemRouteResponses, ItemsRetryItemRouteErrors, ThrowOnError>({
    responseType: 'json',
    url: '/items/{item_id}/retry',
    ...options
});

/**
 * Approve Item
 */
export const itemsApproveItem = <ThrowOnError extends boolean = false>(options: Options<ItemsApproveItemData, ThrowOnError>): RequestResult<ItemsApproveItemResponses, ItemsApproveItemErrors, ThrowOnError> => (options.client ?? client).post<ItemsApproveItemResponses, ItemsApproveItemErrors, ThrowOnError>({
    responseType: 'json',
    url: '/items/{item_id}/approve',
    ...options
});

/**
 * Reject Item
 */
export const itemsRejectItem = <ThrowOnError extends boolean = false>(options: Options<ItemsRejectItemData, ThrowOnError>): RequestResult<ItemsRejectItemResponses, ItemsRejectItemErrors, ThrowOnError> => (options.client ?? client).post<ItemsRejectItemResponses, ItemsRejectItemErrors, ThrowOnError>({
    responseType: 'json',
    url: '/items/{item_id}/reject',
    ...options
});

/**
 * Apply Item Route
 *
 * Write an approved item's staged enrichment back to Tillin (Xano).
 */
export const itemsApplyItemRoute = <ThrowOnError extends boolean = false>(options: Options<ItemsApplyItemRouteData, ThrowOnError>): RequestResult<ItemsApplyItemRouteResponses, ItemsApplyItemRouteErrors, ThrowOnError> => (options.client ?? client).post<ItemsApplyItemRouteResponses, ItemsApplyItemRouteErrors, ThrowOnError>({
    responseType: 'json',
    url: '/items/{item_id}/apply',
    ...options
});
