// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AccountSettings
 *
 * Boutique-level enrichment defaults (stored on account.settings_json).
 */
export type AccountSettings = {
    /**
     * Title Template
     */
    title_template?: string | null;
    /**
     * Title Case
     */
    title_case?: 'none' | 'upper' | 'capitalize';
    /**
     * Editorial Instructions
     */
    editorial_instructions?: string | null;
    /**
     * Client Context
     */
    client_context?: string | null;
    /**
     * Meta Max Length
     */
    meta_max_length?: number;
    /**
     * Notify On Job Done
     */
    notify_on_job_done?: boolean;
    /**
     * Notify Email
     */
    notify_email?: string | null;
    /**
     * Billing Coefficient
     */
    billing_coefficient?: number;
    /**
     * Billing Day
     */
    billing_day?: number;
};

/**
 * AssetSaveRequest
 *
 * POST /imaging/assets/{id}/save body.
 */
export type AssetSaveRequest = {
    /**
     * Replace
     */
    replace?: boolean;
};

/**
 * AssetSaveResult
 *
 * Outcome of pushing a completed asset to Tillin (Xano bulk upload).
 */
export type AssetSaveResult = {
    /**
     * Created
     */
    created: number;
    /**
     * Deactivated
     */
    deactivated: number;
    /**
     * Images
     */
    images?: Array<ProductImage>;
};

/**
 * Body_imports-create_import
 */
export type BodyImportsCreateImport = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Location Id
     */
    location_id?: number | null;
};

/**
 * Body_products-upload_product_images
 */
export type BodyProductsUploadProductImages = {
    /**
     * Files
     *
     * Image files to upload
     */
    files: Array<Blob | File>;
};

/**
 * Brand
 *
 * The brand a product belongs to, with its source website(s).
 */
export type Brand = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Website Urls
     */
    website_urls?: Array<string>;
};

/**
 * BrandPublic
 *
 * A Tillin brand with its reference website URLs.
 */
export type BrandPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Website Urls
     */
    website_urls?: Array<string>;
};

/**
 * BrandWebsiteUrlsUpdate
 *
 * Replace a brand's reference website URLs.
 */
export type BrandWebsiteUrlsUpdate = {
    /**
     * Website Urls
     */
    website_urls: Array<string>;
};

/**
 * CatalogFilters
 *
 * Classification lists backing the product-search filters.
 */
export type CatalogFilters = {
    /**
     * Brands
     */
    brands?: Array<FilterOption>;
    /**
     * Categories
     */
    categories?: Array<FilterOption>;
    /**
     * Compositions
     */
    compositions?: Array<FilterOption>;
    /**
     * Seasons
     */
    seasons?: Array<FilterOption>;
    /**
     * Suppliers
     */
    suppliers?: Array<FilterOption>;
    /**
     * Tags
     */
    tags?: Array<FilterOption>;
};

/**
 * ConnectionStatus
 *
 * Read-only Tillin/Xano connection health (no secrets).
 */
export type ConnectionStatus = {
    /**
     * Configured
     */
    configured: boolean;
    /**
     * Host
     */
    host?: string | null;
    /**
     * Data Source
     */
    data_source?: string | null;
};

/**
 * DashboardStats
 *
 * Account-scoped headline numbers for the dashboard KPI row.
 */
export type DashboardStats = {
    /**
     * Applied Items
     */
    applied_items?: number;
    /**
     * Ready Items
     */
    ready_items?: number;
    /**
     * Running Jobs
     */
    running_jobs?: number;
    /**
     * Jobs Total
     */
    jobs_total?: number;
    /**
     * Items Total
     */
    items_total?: number;
    /**
     * Avg Item Seconds
     */
    avg_item_seconds?: number | null;
    /**
     * Auto Resolve Rate
     */
    auto_resolve_rate?: number | null;
};

/**
 * ExampleResponse
 *
 * Response payload returned by the example endpoint.
 */
export type ExampleResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Sample Id
     */
    sample_id: number;
};

/**
 * FilterOption
 *
 * One selectable value in a search filter (brand, category, …).
 */
export type FilterOption = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Parent Id
     */
    parent_id?: number | null;
};

/**
 * GenerateModelOptions
 *
 * Options of POST /products/{id}/images/generate-model (FASHN).
 */
export type GenerateModelOptions = {
    /**
     * Prompt
     */
    prompt?: string | null;
    /**
     * Aspect Ratio
     */
    aspect_ratio?: string;
    /**
     * Resolution
     */
    resolution?: '1k' | '2k' | '4k';
    /**
     * Generation Mode
     */
    generation_mode?: 'fast' | 'balanced' | 'quality';
    /**
     * Seed
     */
    seed?: number;
    /**
     * Num Images
     */
    num_images?: number;
};

/**
 * GenerateModelRequest
 */
export type GenerateModelRequest = {
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Product Image Id
     */
    product_image_id?: number | null;
    options?: GenerateModelOptions | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Response returned by the healthcheck endpoint.
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: 'ok';
    /**
     * Database
     */
    database: 'up';
};

/**
 * ImageAssetPublic
 *
 * One imaging operation: status + provenance + staged previews.
 */
export type ImageAssetPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Product Id
     */
    product_id: number;
    /**
     * Verb
     */
    verb: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Seed
     */
    seed?: number | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Preview Urls
     */
    preview_urls?: Array<string>;
    /**
     * Source Image
     */
    source_image?: string | null;
    /**
     * Source Product Image Id
     */
    source_product_image_id?: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Finished At
     */
    finished_at?: string | null;
};

/**
 * ImportFilePreview
 */
export type ImportFilePreview = {
    /**
     * Kind
     */
    kind: 'pdf' | 'tabular';
    /**
     * File Name
     */
    file_name: string;
    /**
     * Sheets
     */
    sheets?: Array<ImportFilePreviewSheet>;
};

/**
 * ImportFilePreviewSheet
 */
export type ImportFilePreviewSheet = {
    /**
     * Sheet
     */
    sheet?: string | null;
    /**
     * Rows
     */
    rows?: Array<Array<string>>;
    /**
     * Total Rows
     */
    total_rows?: number;
    /**
     * Truncated
     */
    truncated?: boolean;
};

/**
 * ImportItemPublic
 */
export type ImportItemPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Status
     */
    status: string;
    /**
     * Tillin Product Id
     */
    tillin_product_id?: number | null;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
    /**
     * Warnings
     */
    warnings?: Array<string>;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ImportItemUpdate
 *
 * Review edits: a corrected payload and/or a reject/restore status.
 */
export type ImportItemUpdate = {
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    } | null;
    /**
     * Status
     */
    status?: string | null;
};

/**
 * ImportJobCounts
 */
export type ImportJobCounts = {
    /**
     * Total
     */
    total?: number;
    /**
     * Ready For Review
     */
    ready_for_review?: number;
    /**
     * Failed
     */
    failed?: number;
};

/**
 * ImportJobPublic
 */
export type ImportJobPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Status
     */
    status: string;
    /**
     * File Name
     */
    file_name: string;
    counts: ImportJobCounts;
    totals?: ImportJobTotals;
    /**
     * Po Number
     */
    po_number?: string | null;
    /**
     * Supplier
     */
    supplier?: string | null;
    /**
     * Profile Id
     */
    profile_id?: number | null;
    /**
     * Location Id
     */
    location_id?: number | null;
    /**
     * Warnings
     */
    warnings?: Array<string>;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
};

/**
 * ImportJobTotals
 *
 * Aggregates over every extracted variant (a missing quantity counts
 * as 1 unit; amounts are quantity x unit price, None when no price at all).
 */
export type ImportJobTotals = {
    /**
     * Quantity
     */
    quantity?: number;
    /**
     * Wholesale Amount
     */
    wholesale_amount?: string | null;
    /**
     * Retail Amount
     */
    retail_amount?: string | null;
};

/**
 * ImportLinkResult
 *
 * POST /imports/{id}/link-products outcome (resolution by reference).
 */
export type ImportLinkResult = {
    /**
     * Linked
     */
    linked?: number;
    /**
     * Already Linked
     */
    already_linked?: number;
    /**
     * Not Found
     */
    not_found?: Array<string>;
};

/**
 * ImportLocationSelection
 *
 * PUT /imports/{id}/location body — null clears the selection.
 */
export type ImportLocationSelection = {
    /**
     * Location Id
     */
    location_id: number | null;
};

/**
 * ImportProductLine
 *
 * One row of the « Par import » products view (local data only).
 */
export type ImportProductLine = {
    /**
     * Item Id
     */
    item_id: number;
    /**
     * Status
     */
    status: string;
    /**
     * Supplier Ref
     */
    supplier_ref: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Brand
     */
    brand?: string | null;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Variant Count
     */
    variant_count?: number;
    /**
     * Tillin Product Id
     */
    tillin_product_id?: number | null;
};

/**
 * ImportProducts
 */
export type ImportProducts = {
    /**
     * Import Id
     */
    import_id: number;
    /**
     * File Name
     */
    file_name: string;
    /**
     * Items
     */
    items?: Array<ImportProductLine>;
    /**
     * Linked Count
     */
    linked_count?: number;
    /**
     * Unlinked Count
     */
    unlinked_count?: number;
};

/**
 * ImportProfileConfig
 *
 * Frozen convention shapes; every field has a safe default.
 */
export type ImportProfileConfigInput = {
    /**
     * Price Mode
     */
    price_mode?: 'retail_as_is' | 'coefficient';
    /**
     * Coefficient
     */
    coefficient?: number | string | null;
    /**
     * Round Up To
     */
    round_up_to?: number | string;
    /**
     * Barcode Mode
     */
    barcode_mode?: 'ean' | 'constructed';
    /**
     * Brand Mode
     */
    brand_mode?: 'as_extracted' | 'fixed';
    /**
     * Brand Value
     */
    brand_value?: string;
    /**
     * Supplier Label
     */
    supplier_label?: string;
    /**
     * Season Label
     */
    season_label?: string;
    /**
     * Tax Rate
     */
    tax_rate?: string;
    /**
     * Status
     */
    status?: string;
};

/**
 * ImportProfileConfig
 *
 * Frozen convention shapes; every field has a safe default.
 */
export type ImportProfileConfigOutput = {
    /**
     * Price Mode
     */
    price_mode?: 'retail_as_is' | 'coefficient';
    /**
     * Coefficient
     */
    coefficient?: string | null;
    /**
     * Round Up To
     */
    round_up_to?: string;
    /**
     * Barcode Mode
     */
    barcode_mode?: 'ean' | 'constructed';
    /**
     * Brand Mode
     */
    brand_mode?: 'as_extracted' | 'fixed';
    /**
     * Brand Value
     */
    brand_value?: string;
    /**
     * Supplier Label
     */
    supplier_label?: string;
    /**
     * Season Label
     */
    season_label?: string;
    /**
     * Tax Rate
     */
    tax_rate?: string;
    /**
     * Status
     */
    status?: string;
};

/**
 * ImportProfileCreate
 */
export type ImportProfileCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Supplier Match
     */
    supplier_match?: string;
    config?: ImportProfileConfigInput;
};

/**
 * ImportProfilePublic
 */
export type ImportProfilePublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Supplier Match
     */
    supplier_match: string;
    config: ImportProfileConfigOutput;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ImportProfileSelection
 *
 * PUT /imports/{id}/profile body — null clears the selection.
 */
export type ImportProfileSelection = {
    /**
     * Profile Id
     */
    profile_id: number | null;
};

/**
 * ImportProfileUpdate
 */
export type ImportProfileUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Supplier Match
     */
    supplier_match?: string | null;
    config?: ImportProfileConfigInput | null;
};

/**
 * ImportRenderPreview
 *
 * JSON preview of the rendered Tillin import CSV.
 */
export type ImportRenderPreview = {
    /**
     * Columns
     */
    columns: Array<string>;
    /**
     * Rows
     */
    rows: Array<Array<string>>;
    /**
     * Warnings
     */
    warnings?: Array<string>;
    /**
     * Row Count
     */
    row_count?: number;
};

/**
 * ImportTransferRequest
 *
 * POST /imports/{id}/transfer body.
 *
 * A null location falls back to the job's selected location
 * (config_json["location_id"]); missing both is a 400 `location_required`.
 */
export type ImportTransferRequest = {
    /**
     * Location Id
     */
    location_id?: number | null;
    /**
     * Profile Id
     */
    profile_id?: number | null;
};

/**
 * ImportTransferResult
 */
export type ImportTransferResult = {
    /**
     * Ok
     */
    ok?: boolean;
    /**
     * Row Count
     */
    row_count?: number;
};

/**
 * InstructionCreate
 */
export type InstructionCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Content
     */
    content: string;
    /**
     * Categories
     */
    categories?: Array<string>;
};

/**
 * InstructionPublic
 */
export type InstructionPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Content
     */
    content: string;
    /**
     * Categories
     */
    categories?: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * InstructionUpdate
 */
export type InstructionUpdate = {
    /**
     * Name
     */
    name: string;
    /**
     * Content
     */
    content: string;
    /**
     * Categories
     */
    categories?: Array<string>;
};

/**
 * ItemImageNormalizeRequest
 *
 * Per-image review action: normalize one staged image (or revert it).
 */
export type ItemImageNormalizeRequest = {
    /**
     * Url
     */
    url: string;
    /**
     * Revert
     */
    revert?: boolean;
};

/**
 * ItemPatchRequest
 *
 * Editable staged fields (review-time corrections).
 */
export type ItemPatchRequest = {
    /**
     * Staged Title
     */
    staged_title?: string | null;
    /**
     * Staged Description
     */
    staged_description?: string | null;
    /**
     * Staged Meta
     */
    staged_meta?: string | null;
    /**
     * Staged Images Json
     */
    staged_images_json?: Array<unknown> | null;
    /**
     * Staged Weights Json
     */
    staged_weights_json?: Array<unknown> | null;
    /**
     * Apply Fields Json
     */
    apply_fields_json?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Job Id
     */
    job_id: number;
    /**
     * Tillin Product Id
     */
    tillin_product_id: number;
    /**
     * Status
     */
    status: string;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Source Method
     */
    source_method?: string | null;
    /**
     * Match Score
     */
    match_score?: number | null;
    /**
     * Resolution Json
     */
    resolution_json?: {
        [key: string]: unknown;
    } | null;
    /**
     * Staged Title
     */
    staged_title?: string | null;
    /**
     * Staged Description
     */
    staged_description?: string | null;
    /**
     * Staged Meta
     */
    staged_meta?: string | null;
    /**
     * Staged Images Json
     */
    staged_images_json?: Array<unknown> | null;
    /**
     * Staged Weights Json
     */
    staged_weights_json?: Array<unknown> | null;
    /**
     * Apply Fields Json
     */
    apply_fields_json?: {
        [key: string]: unknown;
    } | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Attempt Count
     */
    attempt_count: number;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ItemResolveRequest
 *
 * Manually point an item at a specific source product page.
 *
 * Any http(s) URL is accepted since the Firecrawl fallback: non-Shopify
 * pages go through LLM extraction (the old validator required a Shopify
 * `/products/` URL and would have blocked e.g. salomon.com in the review).
 */
export type ItemResolveRequest = {
    /**
     * Source Url
     */
    source_url: string;
};

/**
 * JobCounts
 */
export type JobCounts = {
    /**
     * Total
     */
    total?: number;
    /**
     * Pending
     */
    pending?: number;
    /**
     * Processing
     */
    processing?: number;
    /**
     * Ready For Review
     */
    ready_for_review?: number;
    /**
     * Approved
     */
    approved?: number;
    /**
     * Applied
     */
    applied?: number;
    /**
     * Rejected
     */
    rejected?: number;
    /**
     * Failed
     */
    failed?: number;
};

/**
 * JobCreateRequest
 */
export type JobCreateRequest = {
    selection: JobSelection;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
};

/**
 * JobPublic
 */
export type JobPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Status
     */
    status: string;
    /**
     * Selection Json
     */
    selection_json: {
        [key: string]: unknown;
    };
    /**
     * Config Json
     */
    config_json: {
        [key: string]: unknown;
    };
    counts: JobCounts;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
};

/**
 * JobSelection
 *
 * Product selection: explicit Tillin ids or a tag (exactly one).
 */
export type JobSelection = {
    /**
     * Ids
     */
    ids?: Array<number> | null;
    /**
     * Tag
     */
    tag?: string | null;
};

/**
 * LocationPublic
 *
 * A Tillin boutique location a CSV import can be transferred to.
 */
export type LocationPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
};

/**
 * LoginRequest
 *
 * Credentials submitted to the login endpoint.
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * NormalizeOptions
 *
 * Options of POST /products/{id}/images/normalize (Photoroom).
 */
export type NormalizeOptions = {
    /**
     * Bg Color
     */
    bg_color?: string;
    /**
     * Output Size
     */
    output_size?: string;
    /**
     * Padding
     */
    padding?: string;
    /**
     * Format
     */
    format?: string;
    /**
     * Quality
     */
    quality?: number;
    /**
     * Max Kb
     */
    max_kb?: number;
};

/**
 * NormalizeRequest
 */
export type NormalizeRequest = {
    /**
     * Image Url
     */
    image_url: string;
    /**
     * Product Image Id
     */
    product_image_id?: number | null;
    options?: NormalizeOptions | null;
};

/**
 * PaginatedResponse[ImportItemPublic]
 */
export type PaginatedResponseImportItemPublic = {
    /**
     * Items
     */
    items: Array<ImportItemPublic>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
};

/**
 * PaginatedResponse[ImportJobPublic]
 */
export type PaginatedResponseImportJobPublic = {
    /**
     * Items
     */
    items: Array<ImportJobPublic>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
};

/**
 * PaginatedResponse[ItemPublic]
 */
export type PaginatedResponseItemPublic = {
    /**
     * Items
     */
    items: Array<ItemPublic>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
};

/**
 * PaginatedResponse[JobPublic]
 */
export type PaginatedResponseJobPublic = {
    /**
     * Items
     */
    items: Array<JobPublic>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
};

/**
 * PaginatedResponse[Product]
 */
export type PaginatedResponseProduct = {
    /**
     * Items
     */
    items: Array<Product>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
};

/**
 * PasswordChangeRequest
 */
export type PasswordChangeRequest = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * Product
 *
 * Canonical product as consumed by the enrichment/intake engine.
 */
export type Product = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Reference Code
     */
    reference_code?: string | null;
    brand?: Brand | null;
    /**
     * Season
     */
    season?: string | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Department
     */
    department?: string | null;
    /**
     * Composition
     */
    composition?: string | null;
    /**
     * Manufacturing Country
     */
    manufacturing_country?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Meta Description
     */
    meta_description?: string | null;
    /**
     * Price
     */
    price?: string | null;
    /**
     * Variants
     */
    variants?: Array<ProductVariant>;
    /**
     * Images
     */
    images?: Array<ProductImage>;
};

/**
 * ProductImage
 *
 * An image associated with a product.
 */
export type ProductImage = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Url
     */
    url: string;
    /**
     * Position
     */
    position?: number | null;
};

/**
 * ProductImagesUploadResult
 *
 * Outcome of uploading images to a product: the newly created images.
 */
export type ProductImagesUploadResult = {
    /**
     * Created
     */
    created: number;
    /**
     * Images
     */
    images?: Array<ProductImage>;
};

/**
 * ProductVariant
 *
 * A single sellable variant (style x color x size) of a product.
 */
export type ProductVariant = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Sku
     */
    sku?: string | null;
    /**
     * Barcode
     */
    barcode?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Size
     */
    size?: string | null;
    /**
     * Weight
     */
    weight?: number | null;
    /**
     * Weight Unit
     */
    weight_unit?: string | null;
    /**
     * Price
     */
    price?: string | null;
    /**
     * Wholesale Price
     */
    wholesale_price?: string | null;
};

/**
 * UsageByJob
 */
export type UsageByJob = {
    /**
     * Month
     */
    month: string;
    /**
     * Jobs
     */
    jobs: Array<UsageJobLine>;
};

/**
 * UsageJobLine
 */
export type UsageJobLine = {
    /**
     * Job Id
     */
    job_id: number | null;
    /**
     * Job Type
     */
    job_type: string | null;
    /**
     * Label
     */
    label: string;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Input Tokens
     */
    input_tokens: number;
    /**
     * Output Tokens
     */
    output_tokens: number;
    /**
     * Other Metrics
     */
    other_metrics: Array<UsageJobMetric>;
    /**
     * Cost
     */
    cost: string | null;
    /**
     * Billable
     */
    billable: string | null;
};

/**
 * UsageJobMetric
 */
export type UsageJobMetric = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Metric
     */
    metric: string;
    /**
     * Quantity
     */
    quantity: number;
};

/**
 * UsagePriceCreate
 */
export type UsagePriceCreate = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Metric
     */
    metric: string;
    /**
     * Unit Price
     */
    unit_price: number | string;
    /**
     * Currency
     */
    currency?: string;
};

/**
 * UsagePricePublic
 */
export type UsagePricePublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string | null;
    /**
     * Metric
     */
    metric: string;
    /**
     * Unit Price
     */
    unit_price: string;
    /**
     * Currency
     */
    currency: string;
};

/**
 * UsagePriceUpdate
 */
export type UsagePriceUpdate = {
    /**
     * Provider
     */
    provider?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Metric
     */
    metric?: string | null;
    /**
     * Unit Price
     */
    unit_price?: number | string | null;
    /**
     * Currency
     */
    currency?: string | null;
};

/**
 * UsageSummary
 */
export type UsageSummary = {
    /**
     * Month
     */
    month: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Coefficient
     */
    coefficient: number;
    /**
     * Lines
     */
    lines: Array<UsageSummaryLine>;
    totals: UsageTotals;
    /**
     * Unpriced Count
     */
    unpriced_count: number;
    /**
     * Frozen
     */
    frozen?: boolean;
    /**
     * Billing Date
     */
    billing_date: string;
    /**
     * Frozen At
     */
    frozen_at?: string | null;
};

/**
 * UsageSummaryLine
 */
export type UsageSummaryLine = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Model
     */
    model: string | null;
    /**
     * Metric
     */
    metric: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Unit Price
     */
    unit_price: string | null;
    /**
     * Cost
     */
    cost: string | null;
    /**
     * Billable
     */
    billable: string | null;
};

/**
 * UsageTimeseries
 */
export type UsageTimeseries = {
    /**
     * Month
     */
    month: string;
    /**
     * Group By
     */
    group_by: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Series
     */
    series: Array<UsageTimeseriesSeries>;
};

/**
 * UsageTimeseriesPoint
 */
export type UsageTimeseriesPoint = {
    /**
     * Date
     */
    date: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Quantity
     */
    quantity: number;
};

/**
 * UsageTimeseriesSeries
 */
export type UsageTimeseriesSeries = {
    /**
     * Key
     */
    key: string;
    /**
     * Points
     */
    points: Array<UsageTimeseriesPoint>;
};

/**
 * UsageTotals
 */
export type UsageTotals = {
    /**
     * Cost
     */
    cost: string;
    /**
     * Billable
     */
    billable: string;
};

/**
 * UserPreferences
 *
 * Per-user UI preferences (stored on user.preferences_json).
 *
 * Unknown keys in storage are ignored; missing keys take these defaults.
 */
export type UserPreferences = {
    /**
     * Shortcuts Enabled
     */
    shortcuts_enabled?: boolean;
    /**
     * Auto Advance
     */
    auto_advance?: boolean;
    /**
     * Density
     */
    density?: 'comfortable' | 'compact';
    /**
     * Products Per Page
     */
    products_per_page?: number;
};

/**
 * UserPublic
 *
 * Public-facing representation of a user.
 */
export type UserPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VersionResponse
 *
 * Response exposing the running application version metadata.
 */
export type VersionResponse = {
    /**
     * App
     */
    app: string;
    /**
     * Version
     */
    version: string;
    /**
     * Build
     */
    build?: string | null;
    /**
     * Commit
     */
    commit?: string | null;
    /**
     * Branch
     */
    branch?: string | null;
    /**
     * Environment
     */
    environment: string;
};

export type SystemHealthcheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthcheck';
};

export type SystemHealthcheckResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type SystemHealthcheckResponse = SystemHealthcheckResponses[keyof SystemHealthcheckResponses];

export type SystemVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/version';
};

export type SystemVersionResponses = {
    /**
     * Successful Response
     */
    200: VersionResponse;
};

export type SystemVersionResponse = SystemVersionResponses[keyof SystemVersionResponses];

export type ExampleReadExampleData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Sample Id
         */
        sample_id?: number;
    };
    url: '/example';
};

export type ExampleReadExampleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExampleReadExampleError = ExampleReadExampleErrors[keyof ExampleReadExampleErrors];

export type ExampleReadExampleResponses = {
    /**
     * Successful Response
     */
    200: ExampleResponse;
};

export type ExampleReadExampleResponse = ExampleReadExampleResponses[keyof ExampleReadExampleResponses];

export type AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthReadCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthReadCurrentUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthReadCurrentUserError = AuthReadCurrentUserErrors[keyof AuthReadCurrentUserErrors];

export type AuthReadCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type AuthReadCurrentUserResponse = AuthReadCurrentUserResponses[keyof AuthReadCurrentUserResponses];

export type AuthUpdatePasswordData = {
    body: PasswordChangeRequest;
    path?: never;
    query?: never;
    url: '/auth/password';
};

export type AuthUpdatePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthUpdatePasswordError = AuthUpdatePasswordErrors[keyof AuthUpdatePasswordErrors];

export type AuthUpdatePasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AuthUpdatePasswordResponse = AuthUpdatePasswordResponses[keyof AuthUpdatePasswordResponses];

export type ProductsListProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         *
         * Free-text search
         */
        search?: string | null;
        /**
         * Brand
         *
         * Filter by brand id
         */
        brand?: number | null;
        /**
         * Category
         *
         * Filter by category id
         */
        category?: number | null;
        /**
         * Supplier
         *
         * Filter by supplier id
         */
        supplier?: number | null;
        /**
         * Season
         *
         * Filter by season id
         */
        season?: number | null;
        /**
         * Tag
         *
         * Filter by tag id
         */
        tag?: number | null;
        /**
         * Status
         *
         * Filter by status
         */
        status?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/products';
};

export type ProductsListProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsListProductsError = ProductsListProductsErrors[keyof ProductsListProductsErrors];

export type ProductsListProductsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseProduct;
};

export type ProductsListProductsResponse = ProductsListProductsResponses[keyof ProductsListProductsResponses];

export type ProductsReadProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/products/{product_id}';
};

export type ProductsReadProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsReadProductError = ProductsReadProductErrors[keyof ProductsReadProductErrors];

export type ProductsReadProductResponses = {
    /**
     * Successful Response
     */
    200: Product;
};

export type ProductsReadProductResponse = ProductsReadProductResponses[keyof ProductsReadProductResponses];

export type ProductsUploadProductImagesData = {
    body: BodyProductsUploadProductImages;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/products/{product_id}/images';
};

export type ProductsUploadProductImagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsUploadProductImagesError = ProductsUploadProductImagesErrors[keyof ProductsUploadProductImagesErrors];

export type ProductsUploadProductImagesResponses = {
    /**
     * Successful Response
     */
    200: ProductImagesUploadResult;
};

export type ProductsUploadProductImagesResponse = ProductsUploadProductImagesResponses[keyof ProductsUploadProductImagesResponses];

export type ProductsNormalizeImageData = {
    body: NormalizeRequest;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/products/{product_id}/images/normalize';
};

export type ProductsNormalizeImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsNormalizeImageError = ProductsNormalizeImageErrors[keyof ProductsNormalizeImageErrors];

export type ProductsNormalizeImageResponses = {
    /**
     * Successful Response
     */
    200: ImageAssetPublic;
};

export type ProductsNormalizeImageResponse = ProductsNormalizeImageResponses[keyof ProductsNormalizeImageResponses];

export type ProductsGenerateModelImageData = {
    body: GenerateModelRequest;
    path: {
        /**
         * Product Id
         */
        product_id: number;
    };
    query?: never;
    url: '/products/{product_id}/images/generate-model';
};

export type ProductsGenerateModelImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsGenerateModelImageError = ProductsGenerateModelImageErrors[keyof ProductsGenerateModelImageErrors];

export type ProductsGenerateModelImageResponses = {
    /**
     * Successful Response
     */
    202: ImageAssetPublic;
};

export type ProductsGenerateModelImageResponse = ProductsGenerateModelImageResponses[keyof ProductsGenerateModelImageResponses];

export type ImagingReadAssetData = {
    body?: never;
    path: {
        /**
         * Asset Id
         */
        asset_id: number;
    };
    query?: never;
    url: '/imaging/assets/{asset_id}';
};

export type ImagingReadAssetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImagingReadAssetError = ImagingReadAssetErrors[keyof ImagingReadAssetErrors];

export type ImagingReadAssetResponses = {
    /**
     * Successful Response
     */
    200: ImageAssetPublic;
};

export type ImagingReadAssetResponse = ImagingReadAssetResponses[keyof ImagingReadAssetResponses];

export type ImagingReadAssetFileData = {
    body?: never;
    path: {
        /**
         * Asset Id
         */
        asset_id: number;
        /**
         * Index
         */
        index: number;
    };
    query?: never;
    url: '/imaging/assets/{asset_id}/files/{index}';
};

export type ImagingReadAssetFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImagingReadAssetFileError = ImagingReadAssetFileErrors[keyof ImagingReadAssetFileErrors];

export type ImagingReadAssetFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ImagingSaveAssetData = {
    body: AssetSaveRequest;
    path: {
        /**
         * Asset Id
         */
        asset_id: number;
    };
    query?: never;
    url: '/imaging/assets/{asset_id}/save';
};

export type ImagingSaveAssetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImagingSaveAssetError = ImagingSaveAssetErrors[keyof ImagingSaveAssetErrors];

export type ImagingSaveAssetResponses = {
    /**
     * Successful Response
     */
    200: AssetSaveResult;
};

export type ImagingSaveAssetResponse = ImagingSaveAssetResponses[keyof ImagingSaveAssetResponses];

export type BrandsListBrandsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/brands';
};

export type BrandsListBrandsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrandsListBrandsError = BrandsListBrandsErrors[keyof BrandsListBrandsErrors];

export type BrandsListBrandsResponses = {
    /**
     * Response Brands-List Brands
     *
     * Successful Response
     */
    200: Array<BrandPublic>;
};

export type BrandsListBrandsResponse = BrandsListBrandsResponses[keyof BrandsListBrandsResponses];

export type BrandsUpdateBrandWebsiteUrlsData = {
    body: BrandWebsiteUrlsUpdate;
    path: {
        /**
         * Brand Id
         */
        brand_id: number;
    };
    query?: never;
    url: '/brands/{brand_id}/website_urls';
};

export type BrandsUpdateBrandWebsiteUrlsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrandsUpdateBrandWebsiteUrlsError = BrandsUpdateBrandWebsiteUrlsErrors[keyof BrandsUpdateBrandWebsiteUrlsErrors];

export type BrandsUpdateBrandWebsiteUrlsResponses = {
    /**
     * Successful Response
     */
    200: BrandPublic;
};

export type BrandsUpdateBrandWebsiteUrlsResponse = BrandsUpdateBrandWebsiteUrlsResponses[keyof BrandsUpdateBrandWebsiteUrlsResponses];

export type CatalogGetFiltersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/catalog/filters';
};

export type CatalogGetFiltersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CatalogGetFiltersError = CatalogGetFiltersErrors[keyof CatalogGetFiltersErrors];

export type CatalogGetFiltersResponses = {
    /**
     * Successful Response
     */
    200: CatalogFilters;
};

export type CatalogGetFiltersResponse = CatalogGetFiltersResponses[keyof CatalogGetFiltersResponses];

export type JobsListJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/jobs';
};

export type JobsListJobsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsListJobsError = JobsListJobsErrors[keyof JobsListJobsErrors];

export type JobsListJobsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseJobPublic;
};

export type JobsListJobsResponse = JobsListJobsResponses[keyof JobsListJobsResponses];

export type JobsCreateEnrichmentJobData = {
    body: JobCreateRequest;
    path?: never;
    query?: never;
    url: '/jobs';
};

export type JobsCreateEnrichmentJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsCreateEnrichmentJobError = JobsCreateEnrichmentJobErrors[keyof JobsCreateEnrichmentJobErrors];

export type JobsCreateEnrichmentJobResponses = {
    /**
     * Successful Response
     */
    201: JobPublic;
};

export type JobsCreateEnrichmentJobResponse = JobsCreateEnrichmentJobResponses[keyof JobsCreateEnrichmentJobResponses];

export type JobsRetryJobFailuresData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/{job_id}/retry';
};

export type JobsRetryJobFailuresErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsRetryJobFailuresError = JobsRetryJobFailuresErrors[keyof JobsRetryJobFailuresErrors];

export type JobsRetryJobFailuresResponses = {
    /**
     * Successful Response
     */
    200: JobPublic;
};

export type JobsRetryJobFailuresResponse = JobsRetryJobFailuresResponses[keyof JobsRetryJobFailuresResponses];

export type JobsReadJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type JobsReadJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsReadJobError = JobsReadJobErrors[keyof JobsReadJobErrors];

export type JobsReadJobResponses = {
    /**
     * Successful Response
     */
    200: JobPublic;
};

export type JobsReadJobResponse = JobsReadJobResponses[keyof JobsReadJobResponses];

export type JobsListJobItemsData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: {
        /**
         * Status
         */
        status?: 'pending' | 'processing' | 'ready_for_review' | 'approved' | 'applied' | 'rejected' | 'failed';
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/jobs/{job_id}/items';
};

export type JobsListJobItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsListJobItemsError = JobsListJobItemsErrors[keyof JobsListJobItemsErrors];

export type JobsListJobItemsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseItemPublic;
};

export type JobsListJobItemsResponse = JobsListJobItemsResponses[keyof JobsListJobItemsResponses];

export type ImportsListImportsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/imports';
};

export type ImportsListImportsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsListImportsError = ImportsListImportsErrors[keyof ImportsListImportsErrors];

export type ImportsListImportsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseImportJobPublic;
};

export type ImportsListImportsResponse = ImportsListImportsResponses[keyof ImportsListImportsResponses];

export type ImportsCreateImportData = {
    body: BodyImportsCreateImport;
    path?: never;
    query?: never;
    url: '/imports';
};

export type ImportsCreateImportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsCreateImportError = ImportsCreateImportErrors[keyof ImportsCreateImportErrors];

export type ImportsCreateImportResponses = {
    /**
     * Successful Response
     */
    201: ImportJobPublic;
};

export type ImportsCreateImportResponse = ImportsCreateImportResponses[keyof ImportsCreateImportResponses];

export type ImportsReadImportData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: number;
    };
    query?: never;
    url: '/imports/{import_id}';
};

export type ImportsReadImportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsReadImportError = ImportsReadImportErrors[keyof ImportsReadImportErrors];

export type ImportsReadImportResponses = {
    /**
     * Successful Response
     */
    200: ImportJobPublic;
};

export type ImportsReadImportResponse = ImportsReadImportResponses[keyof ImportsReadImportResponses];

export type ImportsDownloadImportFileData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: number;
    };
    query?: never;
    url: '/imports/{import_id}/file';
};

export type ImportsDownloadImportFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsDownloadImportFileError = ImportsDownloadImportFileErrors[keyof ImportsDownloadImportFileErrors];

export type ImportsDownloadImportFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ImportsPreviewImportFileData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: number;
    };
    query?: never;
    url: '/imports/{import_id}/file/preview';
};

export type ImportsPreviewImportFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsPreviewImportFileError = ImportsPreviewImportFileErrors[keyof ImportsPreviewImportFileErrors];

export type ImportsPreviewImportFileResponses = {
    /**
     * Successful Response
     */
    200: ImportFilePreview;
};

export type ImportsPreviewImportFileResponse = ImportsPreviewImportFileResponses[keyof ImportsPreviewImportFileResponses];

export type ImportsListImportItemsData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: number;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/imports/{import_id}/items';
};

export type ImportsListImportItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsListImportItemsError = ImportsListImportItemsErrors[keyof ImportsListImportItemsErrors];

export type ImportsListImportItemsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseImportItemPublic;
};

export type ImportsListImportItemsResponse = ImportsListImportItemsResponses[keyof ImportsListImportItemsResponses];

export type ImportsUpdateImportItemData = {
    body: ImportItemUpdate;
    path: {
        /**
         * Import Id
         */
        import_id: number;
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/imports/{import_id}/items/{item_id}';
};

export type ImportsUpdateImportItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsUpdateImportItemError = ImportsUpdateImportItemErrors[keyof ImportsUpdateImportItemErrors];

export type ImportsUpdateImportItemResponses = {
    /**
     * Successful Response
     */
    200: ImportItemPublic;
};

export type ImportsUpdateImportItemResponse = ImportsUpdateImportItemResponses[keyof ImportsUpdateImportItemResponses];

export type ImportsSetImportProfileData = {
    body: ImportProfileSelection;
    path: {
        /**
         * Import Id
         */
        import_id: number;
    };
    query?: never;
    url: '/imports/{import_id}/profile';
};

export type ImportsSetImportProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsSetImportProfileError = ImportsSetImportProfileErrors[keyof ImportsSetImportProfileErrors];

export type ImportsSetImportProfileResponses = {
    /**
     * Successful Response
     */
    200: ImportJobPublic;
};

export type ImportsSetImportProfileResponse = ImportsSetImportProfileResponses[keyof ImportsSetImportProfileResponses];

export type ImportsSetImportLocationData = {
    body: ImportLocationSelection;
    path: {
        /**
         * Import Id
         */
        import_id: number;
    };
    query?: never;
    url: '/imports/{import_id}/location';
};

export type ImportsSetImportLocationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsSetImportLocationError = ImportsSetImportLocationErrors[keyof ImportsSetImportLocationErrors];

export type ImportsSetImportLocationResponses = {
    /**
     * Successful Response
     */
    200: ImportJobPublic;
};

export type ImportsSetImportLocationResponse = ImportsSetImportLocationResponses[keyof ImportsSetImportLocationResponses];

export type ImportsPreviewImportRowsData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: number;
    };
    query?: {
        /**
         * Profile Id
         */
        profile_id?: number | null;
    };
    url: '/imports/{import_id}/rows';
};

export type ImportsPreviewImportRowsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsPreviewImportRowsError = ImportsPreviewImportRowsErrors[keyof ImportsPreviewImportRowsErrors];

export type ImportsPreviewImportRowsResponses = {
    /**
     * Successful Response
     */
    200: ImportRenderPreview;
};

export type ImportsPreviewImportRowsResponse = ImportsPreviewImportRowsResponses[keyof ImportsPreviewImportRowsResponses];

export type ImportsDownloadImportCsvData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: number;
    };
    query?: {
        /**
         * Profile Id
         */
        profile_id?: number | null;
    };
    url: '/imports/{import_id}/csv';
};

export type ImportsDownloadImportCsvErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsDownloadImportCsvError = ImportsDownloadImportCsvErrors[keyof ImportsDownloadImportCsvErrors];

export type ImportsDownloadImportCsvResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ImportsTransferImportData = {
    body: ImportTransferRequest;
    path: {
        /**
         * Import Id
         */
        import_id: number;
    };
    query?: never;
    url: '/imports/{import_id}/transfer';
};

export type ImportsTransferImportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsTransferImportError = ImportsTransferImportErrors[keyof ImportsTransferImportErrors];

export type ImportsTransferImportResponses = {
    /**
     * Successful Response
     */
    200: ImportTransferResult;
};

export type ImportsTransferImportResponse = ImportsTransferImportResponses[keyof ImportsTransferImportResponses];

export type ImportsLinkImportProductsData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: number;
    };
    query?: never;
    url: '/imports/{import_id}/link-products';
};

export type ImportsLinkImportProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsLinkImportProductsError = ImportsLinkImportProductsErrors[keyof ImportsLinkImportProductsErrors];

export type ImportsLinkImportProductsResponses = {
    /**
     * Successful Response
     */
    200: ImportLinkResult;
};

export type ImportsLinkImportProductsResponse = ImportsLinkImportProductsResponses[keyof ImportsLinkImportProductsResponses];

export type ImportsListImportProductsData = {
    body?: never;
    path: {
        /**
         * Import Id
         */
        import_id: number;
    };
    query?: never;
    url: '/imports/{import_id}/products';
};

export type ImportsListImportProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportsListImportProductsError = ImportsListImportProductsErrors[keyof ImportsListImportProductsErrors];

export type ImportsListImportProductsResponses = {
    /**
     * Successful Response
     */
    200: ImportProducts;
};

export type ImportsListImportProductsResponse = ImportsListImportProductsResponses[keyof ImportsListImportProductsResponses];

export type ImportProfilesListImportProfilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/import-profiles';
};

export type ImportProfilesListImportProfilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportProfilesListImportProfilesError = ImportProfilesListImportProfilesErrors[keyof ImportProfilesListImportProfilesErrors];

export type ImportProfilesListImportProfilesResponses = {
    /**
     * Response Import-Profiles-List Import Profiles
     *
     * Successful Response
     */
    200: Array<ImportProfilePublic>;
};

export type ImportProfilesListImportProfilesResponse = ImportProfilesListImportProfilesResponses[keyof ImportProfilesListImportProfilesResponses];

export type ImportProfilesCreateImportProfileData = {
    body: ImportProfileCreate;
    path?: never;
    query?: never;
    url: '/import-profiles';
};

export type ImportProfilesCreateImportProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportProfilesCreateImportProfileError = ImportProfilesCreateImportProfileErrors[keyof ImportProfilesCreateImportProfileErrors];

export type ImportProfilesCreateImportProfileResponses = {
    /**
     * Successful Response
     */
    201: ImportProfilePublic;
};

export type ImportProfilesCreateImportProfileResponse = ImportProfilesCreateImportProfileResponses[keyof ImportProfilesCreateImportProfileResponses];

export type ImportProfilesDeleteImportProfileData = {
    body?: never;
    path: {
        /**
         * Profile Id
         */
        profile_id: number;
    };
    query?: never;
    url: '/import-profiles/{profile_id}';
};

export type ImportProfilesDeleteImportProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportProfilesDeleteImportProfileError = ImportProfilesDeleteImportProfileErrors[keyof ImportProfilesDeleteImportProfileErrors];

export type ImportProfilesDeleteImportProfileResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ImportProfilesDeleteImportProfileResponse = ImportProfilesDeleteImportProfileResponses[keyof ImportProfilesDeleteImportProfileResponses];

export type ImportProfilesUpdateImportProfileData = {
    body: ImportProfileUpdate;
    path: {
        /**
         * Profile Id
         */
        profile_id: number;
    };
    query?: never;
    url: '/import-profiles/{profile_id}';
};

export type ImportProfilesUpdateImportProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportProfilesUpdateImportProfileError = ImportProfilesUpdateImportProfileErrors[keyof ImportProfilesUpdateImportProfileErrors];

export type ImportProfilesUpdateImportProfileResponses = {
    /**
     * Successful Response
     */
    200: ImportProfilePublic;
};

export type ImportProfilesUpdateImportProfileResponse = ImportProfilesUpdateImportProfileResponses[keyof ImportProfilesUpdateImportProfileResponses];

export type LocationsListLocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/locations';
};

export type LocationsListLocationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LocationsListLocationsError = LocationsListLocationsErrors[keyof LocationsListLocationsErrors];

export type LocationsListLocationsResponses = {
    /**
     * Response Locations-List Locations
     *
     * Successful Response
     */
    200: Array<LocationPublic>;
};

export type LocationsListLocationsResponse = LocationsListLocationsResponses[keyof LocationsListLocationsResponses];

export type ItemsReadItemData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}';
};

export type ItemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors];

export type ItemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses];

export type ItemsPatchItemData = {
    body: ItemPatchRequest;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}';
};

export type ItemsPatchItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsPatchItemError = ItemsPatchItemErrors[keyof ItemsPatchItemErrors];

export type ItemsPatchItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsPatchItemResponse = ItemsPatchItemResponses[keyof ItemsPatchItemResponses];

export type ItemsReadItemProductData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/product';
};

export type ItemsReadItemProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemProductError = ItemsReadItemProductErrors[keyof ItemsReadItemProductErrors];

export type ItemsReadItemProductResponses = {
    /**
     * Successful Response
     */
    200: Product;
};

export type ItemsReadItemProductResponse = ItemsReadItemProductResponses[keyof ItemsReadItemProductResponses];

export type ItemsResolveItemRouteData = {
    body: ItemResolveRequest;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/resolve';
};

export type ItemsResolveItemRouteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsResolveItemRouteError = ItemsResolveItemRouteErrors[keyof ItemsResolveItemRouteErrors];

export type ItemsResolveItemRouteResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsResolveItemRouteResponse = ItemsResolveItemRouteResponses[keyof ItemsResolveItemRouteResponses];

export type ItemsRetryItemRouteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/retry';
};

export type ItemsRetryItemRouteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsRetryItemRouteError = ItemsRetryItemRouteErrors[keyof ItemsRetryItemRouteErrors];

export type ItemsRetryItemRouteResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsRetryItemRouteResponse = ItemsRetryItemRouteResponses[keyof ItemsRetryItemRouteResponses];

export type ItemsNormalizeItemImageRouteData = {
    body: ItemImageNormalizeRequest;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/images/normalize';
};

export type ItemsNormalizeItemImageRouteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsNormalizeItemImageRouteError = ItemsNormalizeItemImageRouteErrors[keyof ItemsNormalizeItemImageRouteErrors];

export type ItemsNormalizeItemImageRouteResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsNormalizeItemImageRouteResponse = ItemsNormalizeItemImageRouteResponses[keyof ItemsNormalizeItemImageRouteResponses];

export type ItemsApproveItemData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/approve';
};

export type ItemsApproveItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsApproveItemError = ItemsApproveItemErrors[keyof ItemsApproveItemErrors];

export type ItemsApproveItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsApproveItemResponse = ItemsApproveItemResponses[keyof ItemsApproveItemResponses];

export type ItemsRejectItemData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/reject';
};

export type ItemsRejectItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsRejectItemError = ItemsRejectItemErrors[keyof ItemsRejectItemErrors];

export type ItemsRejectItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsRejectItemResponse = ItemsRejectItemResponses[keyof ItemsRejectItemResponses];

export type ItemsApplyItemRouteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/apply';
};

export type ItemsApplyItemRouteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsApplyItemRouteError = ItemsApplyItemRouteErrors[keyof ItemsApplyItemRouteErrors];

export type ItemsApplyItemRouteResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsApplyItemRouteResponse = ItemsApplyItemRouteResponses[keyof ItemsApplyItemRouteResponses];

export type StatsDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats/dashboard';
};

export type StatsDashboardStatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StatsDashboardStatsError = StatsDashboardStatsErrors[keyof StatsDashboardStatsErrors];

export type StatsDashboardStatsResponses = {
    /**
     * Successful Response
     */
    200: DashboardStats;
};

export type StatsDashboardStatsResponse = StatsDashboardStatsResponses[keyof StatsDashboardStatsResponses];

export type SettingsReadMyPreferencesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/me';
};

export type SettingsReadMyPreferencesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SettingsReadMyPreferencesError = SettingsReadMyPreferencesErrors[keyof SettingsReadMyPreferencesErrors];

export type SettingsReadMyPreferencesResponses = {
    /**
     * Successful Response
     */
    200: UserPreferences;
};

export type SettingsReadMyPreferencesResponse = SettingsReadMyPreferencesResponses[keyof SettingsReadMyPreferencesResponses];

export type SettingsUpdateMyPreferencesData = {
    body: UserPreferences;
    path?: never;
    query?: never;
    url: '/settings/me';
};

export type SettingsUpdateMyPreferencesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SettingsUpdateMyPreferencesError = SettingsUpdateMyPreferencesErrors[keyof SettingsUpdateMyPreferencesErrors];

export type SettingsUpdateMyPreferencesResponses = {
    /**
     * Successful Response
     */
    200: UserPreferences;
};

export type SettingsUpdateMyPreferencesResponse = SettingsUpdateMyPreferencesResponses[keyof SettingsUpdateMyPreferencesResponses];

export type SettingsReadAccountSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/account';
};

export type SettingsReadAccountSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SettingsReadAccountSettingsError = SettingsReadAccountSettingsErrors[keyof SettingsReadAccountSettingsErrors];

export type SettingsReadAccountSettingsResponses = {
    /**
     * Successful Response
     */
    200: AccountSettings;
};

export type SettingsReadAccountSettingsResponse = SettingsReadAccountSettingsResponses[keyof SettingsReadAccountSettingsResponses];

export type SettingsUpdateAccountSettingsData = {
    body: AccountSettings;
    path?: never;
    query?: never;
    url: '/settings/account';
};

export type SettingsUpdateAccountSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SettingsUpdateAccountSettingsError = SettingsUpdateAccountSettingsErrors[keyof SettingsUpdateAccountSettingsErrors];

export type SettingsUpdateAccountSettingsResponses = {
    /**
     * Successful Response
     */
    200: AccountSettings;
};

export type SettingsUpdateAccountSettingsResponse = SettingsUpdateAccountSettingsResponses[keyof SettingsUpdateAccountSettingsResponses];

export type SettingsReadConnectionStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/connection';
};

export type SettingsReadConnectionStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SettingsReadConnectionStatusError = SettingsReadConnectionStatusErrors[keyof SettingsReadConnectionStatusErrors];

export type SettingsReadConnectionStatusResponses = {
    /**
     * Successful Response
     */
    200: ConnectionStatus;
};

export type SettingsReadConnectionStatusResponse = SettingsReadConnectionStatusResponses[keyof SettingsReadConnectionStatusResponses];

export type InstructionsListInstructionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/instructions';
};

export type InstructionsListInstructionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InstructionsListInstructionsError = InstructionsListInstructionsErrors[keyof InstructionsListInstructionsErrors];

export type InstructionsListInstructionsResponses = {
    /**
     * Response Instructions-List Instructions
     *
     * Successful Response
     */
    200: Array<InstructionPublic>;
};

export type InstructionsListInstructionsResponse = InstructionsListInstructionsResponses[keyof InstructionsListInstructionsResponses];

export type InstructionsCreateInstructionData = {
    body: InstructionCreate;
    path?: never;
    query?: never;
    url: '/instructions';
};

export type InstructionsCreateInstructionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InstructionsCreateInstructionError = InstructionsCreateInstructionErrors[keyof InstructionsCreateInstructionErrors];

export type InstructionsCreateInstructionResponses = {
    /**
     * Successful Response
     */
    201: InstructionPublic;
};

export type InstructionsCreateInstructionResponse = InstructionsCreateInstructionResponses[keyof InstructionsCreateInstructionResponses];

export type InstructionsDeleteInstructionData = {
    body?: never;
    path: {
        /**
         * Instruction Id
         */
        instruction_id: number;
    };
    query?: never;
    url: '/instructions/{instruction_id}';
};

export type InstructionsDeleteInstructionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InstructionsDeleteInstructionError = InstructionsDeleteInstructionErrors[keyof InstructionsDeleteInstructionErrors];

export type InstructionsDeleteInstructionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type InstructionsDeleteInstructionResponse = InstructionsDeleteInstructionResponses[keyof InstructionsDeleteInstructionResponses];

export type InstructionsUpdateInstructionData = {
    body: InstructionUpdate;
    path: {
        /**
         * Instruction Id
         */
        instruction_id: number;
    };
    query?: never;
    url: '/instructions/{instruction_id}';
};

export type InstructionsUpdateInstructionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InstructionsUpdateInstructionError = InstructionsUpdateInstructionErrors[keyof InstructionsUpdateInstructionErrors];

export type InstructionsUpdateInstructionResponses = {
    /**
     * Successful Response
     */
    200: InstructionPublic;
};

export type InstructionsUpdateInstructionResponse = InstructionsUpdateInstructionResponses[keyof InstructionsUpdateInstructionResponses];

export type UsageListUsagePricesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/usage/prices';
};

export type UsageListUsagePricesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsageListUsagePricesError = UsageListUsagePricesErrors[keyof UsageListUsagePricesErrors];

export type UsageListUsagePricesResponses = {
    /**
     * Response Usage-List Usage Prices
     *
     * Successful Response
     */
    200: Array<UsagePricePublic>;
};

export type UsageListUsagePricesResponse = UsageListUsagePricesResponses[keyof UsageListUsagePricesResponses];

export type UsageCreateUsagePriceData = {
    body: UsagePriceCreate;
    path?: never;
    query?: never;
    url: '/usage/prices';
};

export type UsageCreateUsagePriceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsageCreateUsagePriceError = UsageCreateUsagePriceErrors[keyof UsageCreateUsagePriceErrors];

export type UsageCreateUsagePriceResponses = {
    /**
     * Successful Response
     */
    201: UsagePricePublic;
};

export type UsageCreateUsagePriceResponse = UsageCreateUsagePriceResponses[keyof UsageCreateUsagePriceResponses];

export type UsageDeleteUsagePriceData = {
    body?: never;
    path: {
        /**
         * Price Id
         */
        price_id: number;
    };
    query?: never;
    url: '/usage/prices/{price_id}';
};

export type UsageDeleteUsagePriceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsageDeleteUsagePriceError = UsageDeleteUsagePriceErrors[keyof UsageDeleteUsagePriceErrors];

export type UsageDeleteUsagePriceResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsageDeleteUsagePriceResponse = UsageDeleteUsagePriceResponses[keyof UsageDeleteUsagePriceResponses];

export type UsageUpdateUsagePriceData = {
    body: UsagePriceUpdate;
    path: {
        /**
         * Price Id
         */
        price_id: number;
    };
    query?: never;
    url: '/usage/prices/{price_id}';
};

export type UsageUpdateUsagePriceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsageUpdateUsagePriceError = UsageUpdateUsagePriceErrors[keyof UsageUpdateUsagePriceErrors];

export type UsageUpdateUsagePriceResponses = {
    /**
     * Successful Response
     */
    200: UsagePricePublic;
};

export type UsageUpdateUsagePriceResponse = UsageUpdateUsagePriceResponses[keyof UsageUpdateUsagePriceResponses];

export type UsageReadUsageSummaryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Month
         */
        month?: string | null;
    };
    url: '/usage/summary';
};

export type UsageReadUsageSummaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsageReadUsageSummaryError = UsageReadUsageSummaryErrors[keyof UsageReadUsageSummaryErrors];

export type UsageReadUsageSummaryResponses = {
    /**
     * Successful Response
     */
    200: UsageSummary;
};

export type UsageReadUsageSummaryResponse = UsageReadUsageSummaryResponses[keyof UsageReadUsageSummaryResponses];

export type UsageReadUsageByJobData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Month
         */
        month?: string | null;
    };
    url: '/usage/by-job';
};

export type UsageReadUsageByJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsageReadUsageByJobError = UsageReadUsageByJobErrors[keyof UsageReadUsageByJobErrors];

export type UsageReadUsageByJobResponses = {
    /**
     * Successful Response
     */
    200: UsageByJob;
};

export type UsageReadUsageByJobResponse = UsageReadUsageByJobResponses[keyof UsageReadUsageByJobResponses];

export type UsageExportUsageCsvData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Month
         */
        month?: string | null;
    };
    url: '/usage/export';
};

export type UsageExportUsageCsvErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsageExportUsageCsvError = UsageExportUsageCsvErrors[keyof UsageExportUsageCsvErrors];

export type UsageExportUsageCsvResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsageRefreezeSnapshotData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Month
         */
        month: string;
    };
    url: '/usage/snapshot';
};

export type UsageRefreezeSnapshotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsageRefreezeSnapshotError = UsageRefreezeSnapshotErrors[keyof UsageRefreezeSnapshotErrors];

export type UsageRefreezeSnapshotResponses = {
    /**
     * Successful Response
     */
    200: UsageSummary;
};

export type UsageRefreezeSnapshotResponse = UsageRefreezeSnapshotResponses[keyof UsageRefreezeSnapshotResponses];

export type UsageReadUsageTimeseriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Month
         */
        month?: string | null;
        /**
         * Group By
         */
        group_by?: string;
    };
    url: '/usage/timeseries';
};

export type UsageReadUsageTimeseriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsageReadUsageTimeseriesError = UsageReadUsageTimeseriesErrors[keyof UsageReadUsageTimeseriesErrors];

export type UsageReadUsageTimeseriesResponses = {
    /**
     * Successful Response
     */
    200: UsageTimeseries;
};

export type UsageReadUsageTimeseriesResponse = UsageReadUsageTimeseriesResponses[keyof UsageReadUsageTimeseriesResponses];
