// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ExampleResponse
 *
 * Response payload returned by the example endpoint.
 */
export type ExampleResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Sample Id
     */
    sample_id: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Response returned by the healthcheck endpoint.
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: 'ok';
    /**
     * Database
     */
    database: 'up';
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VersionResponse
 *
 * Response exposing the running application version metadata.
 */
export type VersionResponse = {
    /**
     * App
     */
    app: string;
    /**
     * Version
     */
    version: string;
    /**
     * Build
     */
    build?: string | null;
    /**
     * Commit
     */
    commit?: string | null;
    /**
     * Branch
     */
    branch?: string | null;
    /**
     * Environment
     */
    environment: string;
};

export type SystemHealthcheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthcheck';
};

export type SystemHealthcheckResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type SystemHealthcheckResponse = SystemHealthcheckResponses[keyof SystemHealthcheckResponses];

export type SystemVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/version';
};

export type SystemVersionResponses = {
    /**
     * Successful Response
     */
    200: VersionResponse;
};

export type SystemVersionResponse = SystemVersionResponses[keyof SystemVersionResponses];

export type ExampleReadExampleData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Sample Id
         */
        sample_id?: number;
    };
    url: '/example';
};

export type ExampleReadExampleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExampleReadExampleError = ExampleReadExampleErrors[keyof ExampleReadExampleErrors];

export type ExampleReadExampleResponses = {
    /**
     * Successful Response
     */
    200: ExampleResponse;
};

export type ExampleReadExampleResponse = ExampleReadExampleResponses[keyof ExampleReadExampleResponses];
