// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Brand
 *
 * The brand a product belongs to, with its source website(s).
 */
export type Brand = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Website Urls
     */
    website_urls?: Array<string>;
};

/**
 * CatalogFilters
 *
 * Classification lists backing the product-search filters.
 */
export type CatalogFilters = {
    /**
     * Brands
     */
    brands?: Array<FilterOption>;
    /**
     * Categories
     */
    categories?: Array<FilterOption>;
    /**
     * Seasons
     */
    seasons?: Array<FilterOption>;
    /**
     * Suppliers
     */
    suppliers?: Array<FilterOption>;
    /**
     * Tags
     */
    tags?: Array<FilterOption>;
};

/**
 * DashboardStats
 *
 * Account-scoped headline numbers for the dashboard KPI row.
 */
export type DashboardStats = {
    /**
     * Applied Items
     */
    applied_items?: number;
    /**
     * Ready Items
     */
    ready_items?: number;
    /**
     * Running Jobs
     */
    running_jobs?: number;
    /**
     * Jobs Total
     */
    jobs_total?: number;
    /**
     * Items Total
     */
    items_total?: number;
    /**
     * Avg Item Seconds
     */
    avg_item_seconds?: number | null;
    /**
     * Auto Resolve Rate
     */
    auto_resolve_rate?: number | null;
};

/**
 * ExampleResponse
 *
 * Response payload returned by the example endpoint.
 */
export type ExampleResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Sample Id
     */
    sample_id: number;
};

/**
 * FilterOption
 *
 * One selectable value in a search filter (brand, category, …).
 */
export type FilterOption = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Parent Id
     */
    parent_id?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Response returned by the healthcheck endpoint.
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: 'ok';
    /**
     * Database
     */
    database: 'up';
};

/**
 * ItemPatchRequest
 *
 * Editable staged fields (review-time corrections).
 */
export type ItemPatchRequest = {
    /**
     * Staged Title
     */
    staged_title?: string | null;
    /**
     * Staged Description
     */
    staged_description?: string | null;
    /**
     * Staged Meta
     */
    staged_meta?: string | null;
    /**
     * Staged Images Json
     */
    staged_images_json?: Array<unknown> | null;
    /**
     * Staged Weights Json
     */
    staged_weights_json?: Array<unknown> | null;
    /**
     * Apply Fields Json
     */
    apply_fields_json?: {
        [key: string]: boolean;
    } | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Job Id
     */
    job_id: number;
    /**
     * Tillin Product Id
     */
    tillin_product_id: number;
    /**
     * Status
     */
    status: string;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Source Method
     */
    source_method?: string | null;
    /**
     * Match Score
     */
    match_score?: number | null;
    /**
     * Resolution Json
     */
    resolution_json?: {
        [key: string]: unknown;
    } | null;
    /**
     * Staged Title
     */
    staged_title?: string | null;
    /**
     * Staged Description
     */
    staged_description?: string | null;
    /**
     * Staged Meta
     */
    staged_meta?: string | null;
    /**
     * Staged Images Json
     */
    staged_images_json?: Array<unknown> | null;
    /**
     * Staged Weights Json
     */
    staged_weights_json?: Array<unknown> | null;
    /**
     * Apply Fields Json
     */
    apply_fields_json?: {
        [key: string]: boolean;
    } | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Attempt Count
     */
    attempt_count: number;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ItemResolveRequest
 *
 * Manually point an item at a specific source product page.
 */
export type ItemResolveRequest = {
    /**
     * Source Url
     */
    source_url: string;
};

/**
 * JobCounts
 */
export type JobCounts = {
    /**
     * Total
     */
    total?: number;
    /**
     * Pending
     */
    pending?: number;
    /**
     * Processing
     */
    processing?: number;
    /**
     * Ready For Review
     */
    ready_for_review?: number;
    /**
     * Approved
     */
    approved?: number;
    /**
     * Applied
     */
    applied?: number;
    /**
     * Rejected
     */
    rejected?: number;
    /**
     * Failed
     */
    failed?: number;
};

/**
 * JobCreateRequest
 */
export type JobCreateRequest = {
    selection: JobSelection;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
};

/**
 * JobPublic
 */
export type JobPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Status
     */
    status: string;
    /**
     * Selection Json
     */
    selection_json: {
        [key: string]: unknown;
    };
    /**
     * Config Json
     */
    config_json: {
        [key: string]: unknown;
    };
    counts: JobCounts;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
};

/**
 * JobSelection
 *
 * Product selection: explicit Tillin ids or a tag (exactly one).
 */
export type JobSelection = {
    /**
     * Ids
     */
    ids?: Array<number> | null;
    /**
     * Tag
     */
    tag?: string | null;
};

/**
 * LoginRequest
 *
 * Credentials submitted to the login endpoint.
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * PaginatedResponse[ItemPublic]
 */
export type PaginatedResponseItemPublic = {
    /**
     * Items
     */
    items: Array<ItemPublic>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
};

/**
 * PaginatedResponse[JobPublic]
 */
export type PaginatedResponseJobPublic = {
    /**
     * Items
     */
    items: Array<JobPublic>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
};

/**
 * PaginatedResponse[Product]
 */
export type PaginatedResponseProduct = {
    /**
     * Items
     */
    items: Array<Product>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    /**
     * Total Pages
     */
    total_pages: number;
};

/**
 * Product
 *
 * Canonical product as consumed by the enrichment/intake engine.
 */
export type Product = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Reference Code
     */
    reference_code?: string | null;
    brand?: Brand | null;
    /**
     * Season
     */
    season?: string | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Department
     */
    department?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Meta Description
     */
    meta_description?: string | null;
    /**
     * Variants
     */
    variants?: Array<ProductVariant>;
    /**
     * Images
     */
    images?: Array<ProductImage>;
};

/**
 * ProductImage
 *
 * An image associated with a product.
 */
export type ProductImage = {
    /**
     * Url
     */
    url: string;
    /**
     * Position
     */
    position?: number | null;
};

/**
 * ProductVariant
 *
 * A single sellable variant (style x color x size) of a product.
 */
export type ProductVariant = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Sku
     */
    sku?: string | null;
    /**
     * Barcode
     */
    barcode?: string | null;
    /**
     * Weight
     */
    weight?: number | null;
    /**
     * Weight Unit
     */
    weight_unit?: string | null;
};

/**
 * UserPublic
 *
 * Public-facing representation of a user.
 */
export type UserPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VersionResponse
 *
 * Response exposing the running application version metadata.
 */
export type VersionResponse = {
    /**
     * App
     */
    app: string;
    /**
     * Version
     */
    version: string;
    /**
     * Build
     */
    build?: string | null;
    /**
     * Commit
     */
    commit?: string | null;
    /**
     * Branch
     */
    branch?: string | null;
    /**
     * Environment
     */
    environment: string;
};

export type SystemHealthcheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthcheck';
};

export type SystemHealthcheckResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type SystemHealthcheckResponse = SystemHealthcheckResponses[keyof SystemHealthcheckResponses];

export type SystemVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/version';
};

export type SystemVersionResponses = {
    /**
     * Successful Response
     */
    200: VersionResponse;
};

export type SystemVersionResponse = SystemVersionResponses[keyof SystemVersionResponses];

export type ExampleReadExampleData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Sample Id
         */
        sample_id?: number;
    };
    url: '/example';
};

export type ExampleReadExampleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExampleReadExampleError = ExampleReadExampleErrors[keyof ExampleReadExampleErrors];

export type ExampleReadExampleResponses = {
    /**
     * Successful Response
     */
    200: ExampleResponse;
};

export type ExampleReadExampleResponse = ExampleReadExampleResponses[keyof ExampleReadExampleResponses];

export type AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthReadCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthReadCurrentUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthReadCurrentUserError = AuthReadCurrentUserErrors[keyof AuthReadCurrentUserErrors];

export type AuthReadCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type AuthReadCurrentUserResponse = AuthReadCurrentUserResponses[keyof AuthReadCurrentUserResponses];

export type ProductsListProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         *
         * Free-text search
         */
        search?: string | null;
        /**
         * Brand
         *
         * Filter by brand id
         */
        brand?: number | null;
        /**
         * Category
         *
         * Filter by category id
         */
        category?: number | null;
        /**
         * Supplier
         *
         * Filter by supplier id
         */
        supplier?: number | null;
        /**
         * Season
         *
         * Filter by season id
         */
        season?: number | null;
        /**
         * Tag
         *
         * Filter by tag id
         */
        tag?: number | null;
        /**
         * Status
         *
         * Filter by status
         */
        status?: string | null;
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/products';
};

export type ProductsListProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsListProductsError = ProductsListProductsErrors[keyof ProductsListProductsErrors];

export type ProductsListProductsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseProduct;
};

export type ProductsListProductsResponse = ProductsListProductsResponses[keyof ProductsListProductsResponses];

export type CatalogGetFiltersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/catalog/filters';
};

export type CatalogGetFiltersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CatalogGetFiltersError = CatalogGetFiltersErrors[keyof CatalogGetFiltersErrors];

export type CatalogGetFiltersResponses = {
    /**
     * Successful Response
     */
    200: CatalogFilters;
};

export type CatalogGetFiltersResponse = CatalogGetFiltersResponses[keyof CatalogGetFiltersResponses];

export type JobsListJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/jobs';
};

export type JobsListJobsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsListJobsError = JobsListJobsErrors[keyof JobsListJobsErrors];

export type JobsListJobsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseJobPublic;
};

export type JobsListJobsResponse = JobsListJobsResponses[keyof JobsListJobsResponses];

export type JobsCreateEnrichmentJobData = {
    body: JobCreateRequest;
    path?: never;
    query?: never;
    url: '/jobs';
};

export type JobsCreateEnrichmentJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsCreateEnrichmentJobError = JobsCreateEnrichmentJobErrors[keyof JobsCreateEnrichmentJobErrors];

export type JobsCreateEnrichmentJobResponses = {
    /**
     * Successful Response
     */
    201: JobPublic;
};

export type JobsCreateEnrichmentJobResponse = JobsCreateEnrichmentJobResponses[keyof JobsCreateEnrichmentJobResponses];

export type JobsRetryJobFailuresData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/{job_id}/retry';
};

export type JobsRetryJobFailuresErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsRetryJobFailuresError = JobsRetryJobFailuresErrors[keyof JobsRetryJobFailuresErrors];

export type JobsRetryJobFailuresResponses = {
    /**
     * Successful Response
     */
    200: JobPublic;
};

export type JobsRetryJobFailuresResponse = JobsRetryJobFailuresResponses[keyof JobsRetryJobFailuresResponses];

export type JobsReadJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type JobsReadJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsReadJobError = JobsReadJobErrors[keyof JobsReadJobErrors];

export type JobsReadJobResponses = {
    /**
     * Successful Response
     */
    200: JobPublic;
};

export type JobsReadJobResponse = JobsReadJobResponses[keyof JobsReadJobResponses];

export type JobsListJobItemsData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: {
        /**
         * Status
         */
        status?: 'pending' | 'processing' | 'ready_for_review' | 'approved' | 'applied' | 'rejected' | 'failed';
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/jobs/{job_id}/items';
};

export type JobsListJobItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobsListJobItemsError = JobsListJobItemsErrors[keyof JobsListJobItemsErrors];

export type JobsListJobItemsResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseItemPublic;
};

export type JobsListJobItemsResponse = JobsListJobItemsResponses[keyof JobsListJobItemsResponses];

export type ItemsReadItemData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}';
};

export type ItemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors];

export type ItemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses];

export type ItemsPatchItemData = {
    body: ItemPatchRequest;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}';
};

export type ItemsPatchItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsPatchItemError = ItemsPatchItemErrors[keyof ItemsPatchItemErrors];

export type ItemsPatchItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsPatchItemResponse = ItemsPatchItemResponses[keyof ItemsPatchItemResponses];

export type ItemsReadItemProductData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/product';
};

export type ItemsReadItemProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemProductError = ItemsReadItemProductErrors[keyof ItemsReadItemProductErrors];

export type ItemsReadItemProductResponses = {
    /**
     * Successful Response
     */
    200: Product;
};

export type ItemsReadItemProductResponse = ItemsReadItemProductResponses[keyof ItemsReadItemProductResponses];

export type ItemsResolveItemRouteData = {
    body: ItemResolveRequest;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/resolve';
};

export type ItemsResolveItemRouteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsResolveItemRouteError = ItemsResolveItemRouteErrors[keyof ItemsResolveItemRouteErrors];

export type ItemsResolveItemRouteResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsResolveItemRouteResponse = ItemsResolveItemRouteResponses[keyof ItemsResolveItemRouteResponses];

export type ItemsRetryItemRouteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/retry';
};

export type ItemsRetryItemRouteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsRetryItemRouteError = ItemsRetryItemRouteErrors[keyof ItemsRetryItemRouteErrors];

export type ItemsRetryItemRouteResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsRetryItemRouteResponse = ItemsRetryItemRouteResponses[keyof ItemsRetryItemRouteResponses];

export type ItemsApproveItemData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/approve';
};

export type ItemsApproveItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsApproveItemError = ItemsApproveItemErrors[keyof ItemsApproveItemErrors];

export type ItemsApproveItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsApproveItemResponse = ItemsApproveItemResponses[keyof ItemsApproveItemResponses];

export type ItemsRejectItemData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/reject';
};

export type ItemsRejectItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsRejectItemError = ItemsRejectItemErrors[keyof ItemsRejectItemErrors];

export type ItemsRejectItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsRejectItemResponse = ItemsRejectItemResponses[keyof ItemsRejectItemResponses];

export type ItemsApplyItemRouteData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}/apply';
};

export type ItemsApplyItemRouteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsApplyItemRouteError = ItemsApplyItemRouteErrors[keyof ItemsApplyItemRouteErrors];

export type ItemsApplyItemRouteResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsApplyItemRouteResponse = ItemsApplyItemRouteResponses[keyof ItemsApplyItemRouteResponses];

export type StatsDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats/dashboard';
};

export type StatsDashboardStatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StatsDashboardStatsError = StatsDashboardStatsErrors[keyof StatsDashboardStatsErrors];

export type StatsDashboardStatsResponses = {
    /**
     * Successful Response
     */
    200: DashboardStats;
};

export type StatsDashboardStatsResponse = StatsDashboardStatsResponses[keyof StatsDashboardStatsResponses];
